"use client";

import { ChangeEvent, FormEvent, Suspense, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Film, Image as ImageIcon, UploadCloud, Video } from "lucide-react";

import { AuthProvider, useAuthContext } from "@/components/AuthProvider";
import ProtectedRoute from "@/components/ProtectedRoute";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getOwnedPremiumGroups, type PremiumGroupRecord } from "@/lib/creator-hub";
import { deleteUploadDraft, getUploadDrafts, saveUploadDraft } from "@/lib/drafts";
import { getCreatorToolkitProfile, saveCreatorToolkitProfile, type CreatorToolkitProfile } from "@/lib/media-lab";
import { createPost, getCurrentUserSport } from "@/lib/posts";
import { searchProfiles, type SearchProfile } from "@/lib/user-profile";

const UPLOAD_PRESETS = [
  { value: "highlight", label: "Highlight clip", contentType: "reel", postType: "standard", caption: "New highlight drop", visibility: "public" },
  { value: "recruiting", label: "Recruiting update", contentType: "post", postType: "standard", caption: "Recruiting update", visibility: "public" },
  { value: "team", label: "Team post", contentType: "post", postType: "standard", caption: "Team update", visibility: "public" },
  { value: "poll", label: "Poll", contentType: "post", postType: "poll", caption: "What do you think?", visibility: "public" },
  { value: "qa", label: "Q&A", contentType: "post", postType: "qa", caption: "Drop your answer below.", visibility: "public" },
  { value: "sponsor", label: "Sponsor drop", contentType: "post", postType: "standard", caption: "Partner spotlight", visibility: "public", sponsored: true },
] as const;

const ADVANCED_STUDIO_FIELDS = [
  { key: "sceneDetection", label: "Scene detection" },
  { key: "motionTracking", label: "Motion tracking" },
  { key: "captionStyling", label: "Caption styling" },
  { key: "multiAngleSync", label: "Multi-angle sync" },
  { key: "shotMapOverlay", label: "Shot-map overlay" },
  { key: "statOverlays", label: "Stat overlays" },
  { key: "teamLogoOverlays", label: "Team logo overlays" },
  { key: "ctaOverlays", label: "CTA overlays" },
  { key: "calloutStickers", label: "Callout stickers" },
  { key: "chapterMarkers", label: "Chapter markers" },
  { key: "videoPlaylists", label: "Video playlists" },
  { key: "highlightCollections", label: "Highlight collections" },
  { key: "seasonMixtapes", label: "Season mixtapes" },
  { key: "weeklyRecapBuilder", label: "Weekly recap builder" },
  { key: "creatorRevenueOverlays", label: "Creator revenue overlays" },
  { key: "audioCleanup", label: "Audio cleanup" },
  { key: "noiseReduction", label: "Noise reduction" },
  { key: "autoZoomOnAction", label: "Auto zoom on action" },
  { key: "smartCropForMobile", label: "Smart crop for mobile" },
  { key: "clipLengthOptimizer", label: "Clip length optimizer" },
  { key: "hookSuggestionAi", label: "Hook suggestion AI" },
  { key: "thumbnailTextAi", label: "Thumbnail text AI" },
  { key: "captionAbTesting", label: "Caption A/B testing" },
  { key: "watchTimeAnalytics", label: "Watch-time analytics" },
  { key: "completionRateAnalytics", label: "Completion-rate analytics" },
  { key: "shareRateAnalytics", label: "Share-rate analytics" },
  { key: "saveRateAnalytics", label: "Save-rate analytics" },
  { key: "sponsorClickTracking", label: "Sponsor click-through tracking" },
  { key: "creatorCrmBrands", label: "Creator CRM for brands" },
  { key: "publishingQueue", label: "Publishing queue" },
  { key: "draftReviewWorkflows", label: "Draft review workflows" },
  { key: "brandApprovalFlow", label: "Brand approval flow" },
  { key: "teamMediaApproval", label: "Team media approval" },
  { key: "videoRightsTracker", label: "Video rights tracker" },
  { key: "usageLicensingTracker", label: "Usage licensing tracker" },
  { key: "clipRequestTickets", label: "Clip request tickets" },
  { key: "highlightRequestRouting", label: "Highlight request routing" },
  { key: "fanSubmittedMoments", label: "Fan-submitted moments" },
  { key: "autoGeneratedReels", label: "Auto-generated reels" },
  { key: "shortFormPresets", label: "Short-form export presets" },
  { key: "longFormPresets", label: "Long-form export presets" },
  { key: "socialCoverGenerator", label: "Social cover generator" },
  { key: "promoTrailerBuilder", label: "Promo trailer builder" },
  { key: "trainingMontageBuilder", label: "Training montage builder" },
  { key: "recruitingMontageBuilder", label: "Recruiting montage builder" },
  { key: "sponsorshipMontageBuilder", label: "Sponsorship montage builder" },
  { key: "playerIntroTemplates", label: "Player intro templates" },
  { key: "teamIntroTemplates", label: "Team intro templates" },
  { key: "documentaryTimelines", label: "Documentary timelines" },
  { key: "creatorPortfolioPage", label: "Creator portfolio page" },
  { key: "contentBacklogBoard", label: "Content backlog board" },
  { key: "projectFolders", label: "Project folders" },
  { key: "versionHistory", label: "Version history" },
  { key: "timelineReviewComments", label: "Comment-on-timeline review" },
  { key: "timestampedCoachNotes", label: "Timestamped coach notes" },
  { key: "videoScriptDrafts", label: "Video script drafts" },
  { key: "storyboardBuilder", label: "Storyboard builder" },
  { key: "sceneLabels", label: "Scene labels" },
  { key: "cloudStorageExport", label: "Export to cloud storage" },
  { key: "downloadPermissions", label: "Download permissions" },
  { key: "fanRemixPermissions", label: "Fan remix permissions" },
  { key: "paidVideoPacks", label: "Paid video packs" },
  { key: "subscribersOnlyVideos", label: "Subscribers-only videos" },
  { key: "teamPrivateVideos", label: "Team-private videos" },
  { key: "watermarkedPreviews", label: "Watermarked previews" },
  { key: "leadCaptureOnMedia", label: "Lead capture on media" },
  { key: "productTagsInVideo", label: "Product tags in video" },
  { key: "bookingCtaInVideo", label: "Booking CTA in video" },
] as const;

function UploadPageContent() {
  const { user, loading } = useAuthContext();
  const router = useRouter();
  const searchParams = useSearchParams();
  const [caption, setCaption] = useState("");
  const [sport, setSport] = useState("");
  const [contentType, setContentType] = useState<"post" | "reel">("post");
  const [postType, setPostType] = useState<"standard" | "poll" | "qa">("standard");
  const [questionPrompt, setQuestionPrompt] = useState("");
  const [pollOptions, setPollOptions] = useState(["", ""]);
  const [collaborators, setCollaborators] = useState("");
  const [scheduledFor, setScheduledFor] = useState("");
  const [remixPostId, setRemixPostId] = useState("");
  const [visibility, setVisibility] = useState<"public" | "subscribers" | "premium_group">("public");
  const [premiumGroupId, setPremiumGroupId] = useState("");
  const [sponsored, setSponsored] = useState(false);
  const [sponsorLabel, setSponsorLabel] = useState("");
  const [autoCaption, setAutoCaption] = useState("");
  const [translatedCaption, setTranslatedCaption] = useState("");
  const [accessibilityLabel, setAccessibilityLabel] = useState("");
  const [aiHighlightAnalysis, setAiHighlightAnalysis] = useState("");
  const [voiceoverScript, setVoiceoverScript] = useState("");
  const [thumbnailHint, setThumbnailHint] = useState("");
  const [clipStartSec, setClipStartSec] = useState("");
  const [clipEndSec, setClipEndSec] = useState("");
  const [watermarkEnabled, setWatermarkEnabled] = useState(false);
  const [downloadProtected, setDownloadProtected] = useState(false);
  const [rightClickProtected, setRightClickProtected] = useState(false);
  const [premiumGroups, setPremiumGroups] = useState<PremiumGroupRecord[]>([]);
  const [toolkitProfile, setToolkitProfile] = useState<CreatorToolkitProfile | null>(null);
  const [files, setFiles] = useState<File[]>([]);
  const [previewUrl, setPreviewUrl] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [assistantLoading, setAssistantLoading] = useState<string | null>(null);
  const [profileLoading, setProfileLoading] = useState(true);
  const [loadedDraftId, setLoadedDraftId] = useState<string | null>(null);
  const [playbackSpeed, setPlaybackSpeed] = useState("1");
  const [trimFrameStart, setTrimFrameStart] = useState("0");
  const [trimFrameEnd, setTrimFrameEnd] = useState("");
  const [highlightTags, setHighlightTags] = useState("");
  const [musicSelection, setMusicSelection] = useState("");
  const [introTemplate, setIntroTemplate] = useState("");
  const [outroTemplate, setOutroTemplate] = useState("");
  const [overlaySelection, setOverlaySelection] = useState("");
  const [beforeAfterLabel, setBeforeAfterLabel] = useState("");
  const [comparisonLabel, setComparisonLabel] = useState("");
  const [reactionChainLabel, setReactionChainLabel] = useState("");
  const [spotlightMoment, setSpotlightMoment] = useState("");
  const [playerOfWeekTitle, setPlayerOfWeekTitle] = useState("");
  const [postingPlatform, setPostingPlatform] = useState("HoopLink");
  const [crossPostTargets, setCrossPostTargets] = useState("");
  const [collabInviteForm, setCollabInviteForm] = useState({ creatorName: "", brief: "" });
  const [fanClipRequestForm, setFanClipRequestForm] = useState({ requester: "", clipType: "", note: "" });
  const [clipMarketForm, setClipMarketForm] = useState({ title: "", priceLabel: "", note: "" });
  const [recruitingPackForm, setRecruitingPackForm] = useState({ title: "", audience: "", summary: "" });
  const [calendarForm, setCalendarForm] = useState({ title: "", publishAt: "", platform: "HoopLink" });
  const [advancedStudioMeta, setAdvancedStudioMeta] = useState<Record<string, string>>({});
  const [composerMode, setComposerMode] = useState<"simple" | "advanced">("simple");
  const [selectedPreset, setSelectedPreset] = useState<(typeof UPLOAD_PRESETS)[number]["value"]>("highlight");
  const [recentDrafts, setRecentDrafts] = useState<Array<{ id: string; caption: string; contentType: "post" | "reel" }>>([]);
  const [showCreatorTools, setShowCreatorTools] = useState(false);
  const [profiles, setProfiles] = useState<SearchProfile[]>([]);
  const [collaboratorSearch, setCollaboratorSearch] = useState("");
  const [selectedCollaboratorIds, setSelectedCollaboratorIds] = useState<string[]>([]);
  const [publishProgress, setPublishProgress] = useState(0);
  const [publishStatus, setPublishStatus] = useState("");
  const [failedFiles, setFailedFiles] = useState<string[]>([]);
  const [uploadMode, setUploadMode] = useState<"standard" | "recruiting" | "drill_breakdown" | "before_after" | "stat_card" | "tryout_tape">("standard");
  const [recruitingMeta, setRecruitingMeta] = useState({ position: "", gradYear: "", height: "", team: "", bestSkills: "", coachContactCta: "" });
  const [drillMeta, setDrillMeta] = useState({ drillName: "", goal: "", coachingPoints: "", mistakesToAvoid: "" });
  const [beforeAfterMeta, setBeforeAfterMeta] = useState({ beforeLabel: "", afterLabel: "", improvementNote: "" });
  const [statCardMeta, setStatCardMeta] = useState({ headline: "", statOneLabel: "", statOneValue: "", statTwoLabel: "", statTwoValue: "", statThreeLabel: "", statThreeValue: "" });
  const [coachFeedbackMeta, setCoachFeedbackMeta] = useState({ enabled: false, prompt: "" });
  const [tryoutTapeMeta, setTryoutTapeMeta] = useState({ roleFocus: "", strengths: "", introLine: "" });
  const [verifiedSessionMeta, setVerifiedSessionMeta] = useState({ enabled: false, sessionType: "", sessionLabel: "", verifiedBy: "" });
  const [clipRequestMeta, setClipRequestMeta] = useState({ requestType: "", requesterId: "", requesterLabel: "", requestNote: "" });

  useEffect(() => {
    if (!user) {
      setProfileLoading(false);
      return;
    }

    getCurrentUserSport()
      .then((savedSport) => {
        if (savedSport) {
          setSport(savedSport);
        }
      })
      .then(() => searchProfiles(""))
      .then(setProfiles)
      .then(() => getOwnedPremiumGroups())
      .then(setPremiumGroups)
      .then(() => getCreatorToolkitProfile())
      .then((profile) => {
        setToolkitProfile(profile);
        setAdvancedStudioMeta(
          Object.fromEntries(
            ADVANCED_STUDIO_FIELDS.map(({ key }) => [key, (profile.advancedStudioNotes?.[key] ?? []).join("\n")]),
          ),
        );
      })
      .finally(() => setProfileLoading(false));
  }, [user]);

  useEffect(() => {
    if (!files[0]) {
      setPreviewUrl("");
      return;
    }

    const nextPreviewUrl = URL.createObjectURL(files[0]);
    setPreviewUrl(nextPreviewUrl);

    return () => {
      URL.revokeObjectURL(nextPreviewUrl);
    };
  }, [files]);

  useEffect(() => {
    const draftId = searchParams.get("draft");
    const initialCaption = searchParams.get("caption");
    const remixId = searchParams.get("remix");
    const typeParam = searchParams.get("type");
    const templateParam = searchParams.get("template");

    if (typeParam === "poll" || typeParam === "qa") {
      setPostType(typeParam);
    }

    if (templateParam === "poll") {
      setCaption((current) => current || "What do you think? #poll");
      setPollOptions((current) => current.length >= 2 ? current : ["Option 1", "Option 2"]);
    }

    if (templateParam === "qa") {
      setQuestionPrompt((current) => current || "Ask your community something specific.");
      setCaption((current) => current || "Drop your answer below. #qa");
    }

    if (initialCaption && !caption) {
      setCaption(initialCaption);
    }
    if (remixId && !remixPostId) {
      setRemixPostId(remixId);
      setCaption((current) => current || `Remix on @creator #remix`);
    }
    if (!draftId || loadedDraftId === draftId) {
      return;
    }

    getUploadDrafts().then((drafts) => {
      const draft = drafts.find((item: { id: string }) => item.id === draftId);
      if (!draft) {
        return;
      }

      setCaption(draft.caption);
      setSport(draft.sport);
      setContentType(draft.contentType);
      setPostType(draft.postType ?? "standard");
      setQuestionPrompt(draft.questionPrompt ?? "");
      setPollOptions(draft.pollOptions?.length ? draft.pollOptions : ["", ""]);
      setCollaborators((draft.collaborators ?? []).join(", "));
      setSelectedCollaboratorIds(draft.collaborators ?? []);
      setScheduledFor(draft.scheduledFor ?? "");
      setRemixPostId(draft.remixPostId ?? "");
      setVisibility(draft.visibility ?? "public");
      setPremiumGroupId(draft.premiumGroupId ?? "");
      setSponsored(Boolean(draft.sponsored));
      setSponsorLabel(draft.sponsorLabel ?? "");
      setAutoCaption(draft.autoCaption ?? "");
      setTranslatedCaption(draft.translatedCaption ?? "");
      setAccessibilityLabel(draft.accessibilityLabel ?? "");
      setAiHighlightAnalysis(draft.aiHighlightAnalysis ?? "");
      setVoiceoverScript(draft.voiceoverScript ?? "");
      setThumbnailHint(draft.thumbnailHint ?? "");
      setClipStartSec(draft.clipStartSec ? String(draft.clipStartSec) : "");
      setClipEndSec(draft.clipEndSec ? String(draft.clipEndSec) : "");
      setWatermarkEnabled(Boolean(draft.watermarkEnabled));
      setDownloadProtected(Boolean(draft.downloadProtected));
      setRightClickProtected(Boolean(draft.rightClickProtected));
      setLoadedDraftId(draft.id);
    });
  }, [caption, loadedDraftId, remixPostId, searchParams]);

  useEffect(() => {
    void getUploadDrafts().then((drafts) => {
      setRecentDrafts(
        drafts.slice(0, 3).map((draft: { id: string; caption: string; contentType: "post" | "reel" }) => ({
          id: draft.id,
          caption: draft.caption,
          contentType: draft.contentType,
        }))
      );
    });
  }, [loadedDraftId]);

  const mediaKind = useMemo(() => {
    if (!files[0]) return null;
    return files[0].type.startsWith("video/") ? "video" : "image";
  }, [files]);

  const uploadChecklist = useMemo(
    () => [
      { label: "Media selected", done: files.length > 0 },
      { label: "Caption ready", done: caption.trim().length > 0 },
      { label: "Sport selected", done: sport.trim().length > 0 },
      { label: "Visibility chosen", done: visibility === "public" || visibility === "subscribers" || (visibility === "premium_group" && premiumGroupId.trim().length > 0) },
    ],
    [caption, files.length, premiumGroupId, sport, visibility]
  );

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextFiles = Array.from(event.target.files ?? []);
    setError("");
    setFiles(nextFiles);
    setFailedFiles([]);
  };

  const selectedCollaborators = useMemo(
    () =>
      selectedCollaboratorIds
        .map((id) => profiles.find((profile) => profile.uid === id))
        .filter((profile): profile is SearchProfile => Boolean(profile)),
    [profiles, selectedCollaboratorIds]
  );

  const collaboratorMatches = useMemo(
    () =>
      profiles.filter(
        (profile) =>
          profile.uid !== user?.uid &&
          !selectedCollaboratorIds.includes(profile.uid) &&
          (!collaboratorSearch.trim() ||
            `${profile.displayName} ${profile.username || ""} ${profile.role?.team || ""} ${profile.role?.sport || ""}`
              .toLowerCase()
              .includes(collaboratorSearch.trim().toLowerCase()))
      ),
    [collaboratorSearch, profiles, selectedCollaboratorIds, user?.uid]
  );

  const applyPreset = (presetValue: (typeof UPLOAD_PRESETS)[number]["value"]) => {
    const preset = UPLOAD_PRESETS.find((item) => item.value === presetValue);
    if (!preset) {
      return;
    }

    setSelectedPreset(presetValue);
    setContentType(preset.contentType);
    setPostType(preset.postType);
    setCaption((current) => current || preset.caption);
    setVisibility(preset.visibility);
    setSponsored(Boolean("sponsored" in preset && preset.sponsored));
    setUploadMode(presetValue === "recruiting" ? "recruiting" : presetValue === "highlight" ? "tryout_tape" : "standard");
    if (preset.postType === "poll") {
      setPollOptions((current) => (current.length >= 2 ? current : ["Option 1", "Option 2"]));
    }
    if (preset.postType === "qa") {
      setQuestionPrompt((current) => current || "Ask your community something specific.");
    }
  };

  const runMediaAssist = async (task: "caption_rewrite" | "hashtags" | "translate" | "voiceover" | "thumbnail") => {
    setAssistantLoading(task);
    setError("");
    try {
      const response = await fetch("/api/media-assist", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          task,
          caption,
          sport,
          autoCaption,
          targetLanguage: "Spanish",
        }),
      });
      const data = (await response.json()) as { result?: string; error?: string };
      if (!response.ok) {
        throw new Error(data.error || "Media assist request failed.");
      }
      const result = data.result || "";
      if (task === "caption_rewrite") {
        setCaption(result);
      } else if (task === "hashtags") {
        setCaption((current) => [current.trim(), result.trim()].filter(Boolean).join(" "));
      } else if (task === "translate") {
        setTranslatedCaption(result);
      } else if (task === "voiceover") {
        setVoiceoverScript(result);
      } else if (task === "thumbnail") {
        setThumbnailHint(result);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Media assist failed.");
    } finally {
      setAssistantLoading(null);
    }
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError("");

    const primaryFile = files[0] ?? null;

    if (contentType === "reel" && !primaryFile) {
      setError("Choose a video to upload.");
      return;
    }

    if (contentType === "reel" && primaryFile && !primaryFile.type.startsWith("video/")) {
      setError("Reels must use a video file.");
      return;
    }

    if (postType === "poll" && pollOptions.filter((option) => option.trim()).length < 2) {
      setError("Add at least two poll options.");
      return;
    }

    setSubmitting(true);
    setPublishProgress(0);
    setPublishStatus("");
    setFailedFiles([]);

    try {
      const collaboratorTokens = selectedCollaboratorIds.length
        ? selectedCollaboratorIds
        : collaborators
            .split(",")
            .map((value) => value.trim())
            .filter(Boolean);
      const publishableFiles = files.length ? files : [];
      const totalSteps = Math.max(publishableFiles.length + 1, 2);
      setPublishStatus(
        scheduledFor.trim()
          ? "Queueing your post for scheduled publishing..."
          : publishableFiles.length > 1
            ? "Uploading carousel media..."
            : "Uploading your post..."
      );

      setPublishProgress(10);
      await createPost({
        caption,
        sport,
        file: publishableFiles[0] ?? null,
        files: publishableFiles,
        contentType,
        postType,
        questionPrompt,
        pollOptions,
        collaborators: collaboratorTokens,
        remixPostId,
        scheduledFor,
        visibility,
        premiumGroupId,
        sponsored,
        sponsorLabel,
        autoCaption,
        translatedCaption,
        accessibilityLabel,
        aiHighlightAnalysis,
        voiceoverScript,
        thumbnailHint,
        clipStartSec: clipStartSec ? Number(clipStartSec) : undefined,
        clipEndSec: clipEndSec ? Number(clipEndSec) : undefined,
        watermarkEnabled,
        downloadProtected,
        rightClickProtected,
        uploadMeta: {
          mode: uploadMode,
          recruitingProfile:
            uploadMode === "recruiting"
              ? {
                  position: recruitingMeta.position,
                  gradYear: recruitingMeta.gradYear,
                  height: recruitingMeta.height,
                  team: recruitingMeta.team,
                  bestSkills: recruitingMeta.bestSkills.split(",").map((value) => value.trim()).filter(Boolean),
                  coachContactCta: recruitingMeta.coachContactCta,
                }
              : null,
          drillBreakdown:
            uploadMode === "drill_breakdown"
              ? {
                  drillName: drillMeta.drillName,
                  goal: drillMeta.goal,
                  coachingPoints: drillMeta.coachingPoints.split(",").map((value) => value.trim()).filter(Boolean),
                  mistakesToAvoid: drillMeta.mistakesToAvoid.split(",").map((value) => value.trim()).filter(Boolean),
                }
              : null,
          beforeAfter:
            uploadMode === "before_after"
              ? {
                  beforeLabel: beforeAfterMeta.beforeLabel,
                  afterLabel: beforeAfterMeta.afterLabel,
                  improvementNote: beforeAfterMeta.improvementNote,
                }
              : null,
          statCard:
            uploadMode === "stat_card"
              ? {
                  headline: statCardMeta.headline,
                  stats: [
                    { label: statCardMeta.statOneLabel, value: statCardMeta.statOneValue },
                    { label: statCardMeta.statTwoLabel, value: statCardMeta.statTwoValue },
                    { label: statCardMeta.statThreeLabel, value: statCardMeta.statThreeValue },
                  ].filter((entry) => entry.label.trim() || entry.value.trim()),
                }
              : null,
          coachFeedback: {
            enabled: coachFeedbackMeta.enabled,
            requestedCoachIds: selectedCollaboratorIds.filter((id) => {
              const profile = profiles.find((entry) => entry.uid === id);
              return profile?.role?.type?.toLowerCase() === "coach";
            }),
            prompt: coachFeedbackMeta.prompt,
          },
          tryoutTape:
            uploadMode === "tryout_tape"
              ? {
                  roleFocus: tryoutTapeMeta.roleFocus,
                  strengths: tryoutTapeMeta.strengths.split(",").map((value) => value.trim()).filter(Boolean),
                  introLine: tryoutTapeMeta.introLine,
                }
              : null,
          verifiedSession: {
            enabled: verifiedSessionMeta.enabled,
            sessionType: verifiedSessionMeta.sessionType,
            sessionLabel: verifiedSessionMeta.sessionLabel,
            verifiedBy: verifiedSessionMeta.verifiedBy,
          },
          clipRequest:
            clipRequestMeta.requestType || clipRequestMeta.requesterId || clipRequestMeta.requestNote
              ? {
                  requestType: clipRequestMeta.requestType,
                  requesterId: clipRequestMeta.requesterId,
                  requesterLabel: clipRequestMeta.requesterLabel,
                  requestNote: clipRequestMeta.requestNote,
                }
              : null,
        },
      });
      setPublishProgress(Math.round((totalSteps - 1) / totalSteps * 100));
      setPublishStatus(scheduledFor.trim() ? "Added to your publishing queue." : "Published successfully.");
      setPublishProgress(100);
      if (loadedDraftId) {
        await deleteUploadDraft(loadedDraftId);
      }
      router.push(contentType === "reel" ? "/reels" : "/feed");
    } catch (err) {
      setFailedFiles(files.map((currentFile) => currentFile.name));
      setError(err instanceof Error ? err.message : "Your upload could not be published.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading || profileLoading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="h-10 w-10 animate-spin rounded-full border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <ProtectedRoute>
      <div className="mx-auto max-w-3xl py-8">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <UploadCloud className="h-5 w-5 text-primary" />
              Create content
            </CardTitle>
            <CardDescription>
              Start simple, then open advanced tools only when you need them.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form className="space-y-5" onSubmit={handleSubmit}>
              {recentDrafts.length ? (
                <div className="rounded-xl border bg-muted/30 p-4">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <div>
                      <p className="font-medium">Draft recovery</p>
                      <p className="text-sm text-muted-foreground">Jump back into a saved draft or start fresh.</p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {recentDrafts.map((draft) => (
                        <Link key={draft.id} href={`/upload?draft=${draft.id}`} className="rounded-full border px-3 py-2 text-sm hover:bg-muted/40">
                          {draft.contentType === "reel" ? "Reel" : "Post"}: {draft.caption || "Untitled"}
                        </Link>
                      ))}
                    </div>
                  </div>
                </div>
              ) : null}

              <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4">
                <div>
                  <p className="font-medium">Composer mode</p>
                  <p className="text-sm text-muted-foreground">Keep the default flow light, or open the full toolkit.</p>
                </div>
                <div className="grid grid-cols-2 gap-2 rounded-xl bg-muted p-1">
                  <button
                    type="button"
                    onClick={() => setComposerMode("simple")}
                    className={`rounded-lg px-3 py-2 text-sm ${composerMode === "simple" ? "bg-background shadow-sm" : "text-muted-foreground"}`}
                  >
                    Simple
                  </button>
                  <button
                    type="button"
                    onClick={() => setComposerMode("advanced")}
                    className={`rounded-lg px-3 py-2 text-sm ${composerMode === "advanced" ? "bg-background shadow-sm" : "text-muted-foreground"}`}
                  >
                    Advanced
                  </button>
                </div>
              </div>

              <div className="rounded-xl border p-4">
                <p className="mb-3 font-medium">Quick presets</p>
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                  {UPLOAD_PRESETS.map((preset) => (
                    <button
                      key={preset.value}
                      type="button"
                      onClick={() => applyPreset(preset.value)}
                      className={`rounded-xl border p-3 text-left ${selectedPreset === preset.value ? "border-primary bg-primary/5" : ""}`}
                    >
                      <p className="font-semibold">{preset.label}</p>
                      <p className="text-sm text-muted-foreground">{preset.contentType === "reel" ? "Video-first" : "Feed-ready"}</p>
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setContentType("post")}
                  className={`rounded-xl border p-4 text-left ${contentType === "post" ? "border-primary bg-primary/5" : ""}`}
                >
                  <ImageIcon className="mb-2 h-5 w-5 text-primary" />
                  <p className="font-semibold">Post</p>
                  <p className="text-sm text-muted-foreground">Photos or videos in the main feed.</p>
                </button>
                <button
                  type="button"
                  onClick={() => setContentType("reel")}
                  className={`rounded-xl border p-4 text-left ${contentType === "reel" ? "border-primary bg-primary/5" : ""}`}
                >
                  <Film className="mb-2 h-5 w-5 text-primary" />
                  <p className="font-semibold">Reel</p>
                  <p className="text-sm text-muted-foreground">Vertical video for the reels feed.</p>
                </button>
              </div>

              {contentType === "post" ? (
                <div className="grid grid-cols-3 gap-3">
                  {([
                    { value: "standard", label: "Standard", hint: "Normal post" },
                    { value: "poll", label: "Poll", hint: "Collect votes" },
                    { value: "qa", label: "Q&A", hint: "Ask the community" },
                  ] as const).map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => setPostType(option.value)}
                      className={`rounded-xl border p-4 text-left ${postType === option.value ? "border-primary bg-primary/5" : ""}`}
                    >
                      <p className="font-semibold">{option.label}</p>
                      <p className="text-sm text-muted-foreground">{option.hint}</p>
                    </button>
                  ))}
                </div>
              ) : null}

              <Input
                type="file"
                accept={contentType === "reel" ? "video/*" : "image/*,video/*"}
                onChange={handleFileChange}
                multiple
                disabled={submitting}
              />

              {previewUrl ? (
                <div className="overflow-hidden rounded-xl border bg-muted">
                  {mediaKind === "video" ? (
                    <video src={previewUrl} controls className="max-h-[420px] w-full bg-black object-cover" />
                  ) : (
                    <img src={previewUrl} alt="Upload preview" className="max-h-[420px] w-full object-cover" />
                  )}
                </div>
              ) : (
                <div className="rounded-xl border border-dashed p-8 text-center">
                  {contentType === "reel" ? (
                    <Video className="mx-auto mb-3 h-10 w-10 text-muted-foreground" />
                  ) : (
                    <ImageIcon className="mx-auto mb-3 h-10 w-10 text-muted-foreground" />
                  )}
                  <p className="font-medium">
                    {contentType === "reel" ? "Choose a video for your reel." : "Choose media for your post."}
                  </p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Use hashtags in the caption like `#basketball` to appear in topic feeds.
                  </p>
                </div>
              )}

              {files.length > 1 ? (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-muted-foreground">
                  {files.length} files selected. HoopLink will publish them as one {contentType === "reel" ? "multi-clip reel" : "carousel post"} with swipeable media.
                </div>
              ) : null}

              <div className="rounded-xl border p-4">
                <p className="mb-3 font-medium">HoopLink upload mode</p>
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                  {([
                    { value: "standard", label: "Standard upload", hint: "Normal post or reel" },
                    { value: "recruiting", label: "Recruiting mode", hint: "Position, grad year, skills" },
                    { value: "drill_breakdown", label: "Drill breakdown", hint: "Goal, cues, mistakes" },
                    { value: "before_after", label: "Before / after", hint: "Progress transformation" },
                    { value: "stat_card", label: "Auto stat card", hint: "Numbers-first post" },
                    { value: "tryout_tape", label: "Tryout tape", hint: "Role focus and strengths" },
                  ] as const).map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => setUploadMode(option.value)}
                      className={`rounded-xl border p-3 text-left ${uploadMode === option.value ? "border-primary bg-primary/5" : ""}`}
                    >
                      <p className="font-semibold">{option.label}</p>
                      <p className="text-sm text-muted-foreground">{option.hint}</p>
                    </button>
                  ))}
                </div>
              </div>

              {uploadMode !== "standard" ? (
                <div className="rounded-xl border p-4">
                  <p className="mb-3 font-medium">Mode details</p>
                  {uploadMode === "recruiting" ? (
                    <div className="grid gap-3 md:grid-cols-2">
                      <Input value={recruitingMeta.position} onChange={(event) => setRecruitingMeta((current) => ({ ...current, position: event.target.value }))} placeholder="Position" />
                      <Input value={recruitingMeta.gradYear} onChange={(event) => setRecruitingMeta((current) => ({ ...current, gradYear: event.target.value }))} placeholder="Grad year" />
                      <Input value={recruitingMeta.height} onChange={(event) => setRecruitingMeta((current) => ({ ...current, height: event.target.value }))} placeholder="Height" />
                      <Input value={recruitingMeta.team} onChange={(event) => setRecruitingMeta((current) => ({ ...current, team: event.target.value }))} placeholder="Team" />
                      <Input value={recruitingMeta.bestSkills} onChange={(event) => setRecruitingMeta((current) => ({ ...current, bestSkills: event.target.value }))} placeholder="Best skills, comma separated" />
                      <Input value={recruitingMeta.coachContactCta} onChange={(event) => setRecruitingMeta((current) => ({ ...current, coachContactCta: event.target.value }))} placeholder="Coach contact CTA" />
                    </div>
                  ) : null}
                  {uploadMode === "drill_breakdown" ? (
                    <div className="grid gap-3 md:grid-cols-2">
                      <Input value={drillMeta.drillName} onChange={(event) => setDrillMeta((current) => ({ ...current, drillName: event.target.value }))} placeholder="Drill name" />
                      <Input value={drillMeta.goal} onChange={(event) => setDrillMeta((current) => ({ ...current, goal: event.target.value }))} placeholder="Goal" />
                      <Input value={drillMeta.coachingPoints} onChange={(event) => setDrillMeta((current) => ({ ...current, coachingPoints: event.target.value }))} placeholder="Coaching points, comma separated" />
                      <Input value={drillMeta.mistakesToAvoid} onChange={(event) => setDrillMeta((current) => ({ ...current, mistakesToAvoid: event.target.value }))} placeholder="Mistakes to avoid, comma separated" />
                    </div>
                  ) : null}
                  {uploadMode === "before_after" ? (
                    <div className="grid gap-3 md:grid-cols-2">
                      <Input value={beforeAfterMeta.beforeLabel} onChange={(event) => setBeforeAfterMeta((current) => ({ ...current, beforeLabel: event.target.value }))} placeholder="Before label" />
                      <Input value={beforeAfterMeta.afterLabel} onChange={(event) => setBeforeAfterMeta((current) => ({ ...current, afterLabel: event.target.value }))} placeholder="After label" />
                      <textarea value={beforeAfterMeta.improvementNote} onChange={(event) => setBeforeAfterMeta((current) => ({ ...current, improvementNote: event.target.value }))} placeholder="Improvement note" className="min-h-20 rounded-md border border-input bg-background px-3 py-2 text-sm md:col-span-2" />
                    </div>
                  ) : null}
                  {uploadMode === "stat_card" ? (
                    <div className="grid gap-3 md:grid-cols-2">
                      <Input value={statCardMeta.headline} onChange={(event) => setStatCardMeta((current) => ({ ...current, headline: event.target.value }))} placeholder="Headline" className="md:col-span-2" />
                      <Input value={statCardMeta.statOneLabel} onChange={(event) => setStatCardMeta((current) => ({ ...current, statOneLabel: event.target.value }))} placeholder="Stat 1 label" />
                      <Input value={statCardMeta.statOneValue} onChange={(event) => setStatCardMeta((current) => ({ ...current, statOneValue: event.target.value }))} placeholder="Stat 1 value" />
                      <Input value={statCardMeta.statTwoLabel} onChange={(event) => setStatCardMeta((current) => ({ ...current, statTwoLabel: event.target.value }))} placeholder="Stat 2 label" />
                      <Input value={statCardMeta.statTwoValue} onChange={(event) => setStatCardMeta((current) => ({ ...current, statTwoValue: event.target.value }))} placeholder="Stat 2 value" />
                      <Input value={statCardMeta.statThreeLabel} onChange={(event) => setStatCardMeta((current) => ({ ...current, statThreeLabel: event.target.value }))} placeholder="Stat 3 label" />
                      <Input value={statCardMeta.statThreeValue} onChange={(event) => setStatCardMeta((current) => ({ ...current, statThreeValue: event.target.value }))} placeholder="Stat 3 value" />
                    </div>
                  ) : null}
                  {uploadMode === "tryout_tape" ? (
                    <div className="grid gap-3 md:grid-cols-2">
                      <Input value={tryoutTapeMeta.roleFocus} onChange={(event) => setTryoutTapeMeta((current) => ({ ...current, roleFocus: event.target.value }))} placeholder="Role focus" />
                      <Input value={tryoutTapeMeta.strengths} onChange={(event) => setTryoutTapeMeta((current) => ({ ...current, strengths: event.target.value }))} placeholder="Strengths, comma separated" />
                      <textarea value={tryoutTapeMeta.introLine} onChange={(event) => setTryoutTapeMeta((current) => ({ ...current, introLine: event.target.value }))} placeholder="Intro line / opening pitch" className="min-h-20 rounded-md border border-input bg-background px-3 py-2 text-sm md:col-span-2" />
                    </div>
                  ) : null}
                </div>
              ) : null}

              {files.length > 1 ? (
                <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                  {files.map((file, index) => (
                    <div key={`${file.name}-${index}`} className="rounded-xl border bg-muted/30 p-3 text-sm">
                      <p className="truncate font-medium">{file.name}</p>
                      <p className="text-xs text-muted-foreground">{file.type.startsWith("video/") ? "Video" : "Image"} • slide {index + 1}</p>
                    </div>
                  ))}
                </div>
              ) : null}

              {postType === "qa" && contentType === "post" ? (
                <Input
                  value={questionPrompt}
                  onChange={(event) => setQuestionPrompt(event.target.value)}
                  placeholder="Ask a question to the community"
                  disabled={submitting}
                />
              ) : null}

              {postType === "poll" && contentType === "post" ? (
                <div className="space-y-3 rounded-xl border p-4">
                  <p className="text-sm font-medium">Poll Options</p>
                  {pollOptions.map((option, index) => (
                    <Input
                      key={index}
                      value={option}
                      onChange={(event) =>
                        setPollOptions((current) =>
                          current.map((currentOption, currentIndex) =>
                            currentIndex === index ? event.target.value : currentOption
                          )
                        )
                      }
                      placeholder={`Option ${index + 1}`}
                    />
                  ))}
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setPollOptions((current) => [...current, ""])}
                  >
                    Add Option
                  </Button>
                </div>
              ) : null}

              <Input value={sport} onChange={(event) => setSport(event.target.value)} placeholder="Sport" disabled={submitting} />

              <textarea
                value={caption}
                onChange={(event) => setCaption(event.target.value)}
                placeholder="What happened here? Add #tags so people can discover it."
                disabled={submitting}
                className="min-h-28 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />

              <div className="rounded-xl border p-4">
                <div className="mb-3 flex items-center justify-between gap-3">
                  <div>
                    <p className="font-medium">Caption helper</p>
                    <p className="text-sm text-muted-foreground">Keep AI assist together in one compact place.</p>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setAutoCaption(`${sport || "Sport"} highlight: ${caption || files[0]?.name || "Uploaded clip"}`)}
                  >
                    Quick fill
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button type="button" variant="outline" onClick={() => void runMediaAssist("caption_rewrite")} disabled={assistantLoading !== null}>
                    {assistantLoading === "caption_rewrite" ? "Rewriting..." : "Rewrite"}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void runMediaAssist("hashtags")} disabled={assistantLoading !== null}>
                    {assistantLoading === "hashtags" ? "Suggesting..." : "Hashtags"}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void runMediaAssist("translate")} disabled={assistantLoading !== null}>
                    {assistantLoading === "translate" ? "Translating..." : "Translate"}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void runMediaAssist("thumbnail")} disabled={assistantLoading !== null}>
                    {assistantLoading === "thumbnail" ? "Picking..." : "Thumbnail"}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void runMediaAssist("voiceover")} disabled={assistantLoading !== null}>
                    {assistantLoading === "voiceover" ? "Writing..." : "Voiceover"}
                  </Button>
                </div>
                <div className="mt-3 grid gap-3 md:grid-cols-2">
                  <Input value={autoCaption} onChange={(event) => setAutoCaption(event.target.value)} placeholder="Auto-caption text" disabled={submitting} />
                  <Input value={thumbnailHint} onChange={(event) => setThumbnailHint(event.target.value)} placeholder="Best thumbnail note" disabled={submitting} />
                  <textarea
                    value={translatedCaption}
                    onChange={(event) => setTranslatedCaption(event.target.value)}
                    placeholder="Translated caption"
                    disabled={submitting}
                    className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                  <textarea
                    value={voiceoverScript}
                    onChange={(event) => setVoiceoverScript(event.target.value)}
                    placeholder="Voiceover script"
                    disabled={submitting}
                    className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                </div>
              </div>

              <div className="rounded-xl border p-4">
                <p className="font-medium">Ready to publish?</p>
                <div className="mt-3 grid gap-2 sm:grid-cols-2">
                  {uploadChecklist.map((item) => (
                    <div key={item.label} className={`rounded-lg border px-3 py-2 text-sm ${item.done ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "text-muted-foreground"}`}>
                      {item.done ? "Done" : "Pending"}: {item.label}
                    </div>
                  ))}
                </div>
              </div>

              {(uploadMode !== "standard" || coachFeedbackMeta.enabled || verifiedSessionMeta.enabled || clipRequestMeta.requestType) ? (
                <div className="rounded-xl border bg-muted/20 p-4">
                  <p className="font-medium">HoopLink sports summary</p>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs">
                    <span className="rounded-full bg-primary/5 px-2 py-1 text-primary">Mode: {uploadMode.replace("_", " ")}</span>
                    {coachFeedbackMeta.enabled ? <span className="rounded-full bg-primary/5 px-2 py-1 text-primary">Coach feedback enabled</span> : null}
                    {verifiedSessionMeta.enabled ? <span className="rounded-full bg-primary/5 px-2 py-1 text-primary">Verified session</span> : null}
                    {clipRequestMeta.requestType ? <span className="rounded-full bg-primary/5 px-2 py-1 text-primary">Request: {clipRequestMeta.requestType}</span> : null}
                  </div>
                </div>
              ) : null}

              <div className="rounded-xl border p-4">
                <div className="mb-3">
                  <p className="font-medium">Collaborators</p>
                  <p className="text-sm text-muted-foreground">Search people and add them as tagged collaborators.</p>
                </div>
                {selectedCollaborators.length ? (
                  <div className="mb-3 flex flex-wrap gap-2">
                    {selectedCollaborators.map((profile) => (
                      <button
                        key={profile.uid}
                        type="button"
                        className="rounded-full border bg-muted px-3 py-1.5 text-sm"
                        onClick={() => setSelectedCollaboratorIds((current) => current.filter((id) => id !== profile.uid))}
                      >
                        {profile.displayName} {profile.username ? `(${profile.username})` : ""}
                      </button>
                    ))}
                  </div>
                ) : null}
                <Input
                  value={collaboratorSearch}
                  onChange={(event) => setCollaboratorSearch(event.target.value)}
                  placeholder="Search athletes, coaches, creators..."
                  disabled={submitting}
                />
                <div className="mt-3 flex flex-wrap gap-2">
                  {collaboratorMatches.slice(0, 8).map((profile) => (
                    <button
                      key={profile.uid}
                      type="button"
                      className="rounded-full border px-3 py-1.5 text-sm hover:border-primary/40 hover:bg-primary/5"
                      onClick={() => {
                        setSelectedCollaboratorIds((current) => [...current, profile.uid]);
                        setCollaborators((current) => {
                          const nextTokens = Array.from(new Set([...current.split(",").map((value) => value.trim()).filter(Boolean), profile.uid]));
                          return nextTokens.join(", ");
                        });
                        setCollaboratorSearch("");
                      }}
                    >
                      {profile.displayName} {profile.username ? `• ${profile.username}` : ""}
                    </button>
                  ))}
                  {!collaboratorMatches.slice(0, 8).length ? (
                    <span className="text-sm text-muted-foreground">No more matches yet. You can still paste usernames below.</span>
                  ) : null}
                </div>
                <Input
                  value={collaborators}
                  onChange={(event) => setCollaborators(event.target.value)}
                  placeholder="Optional: paste usernames or UIDs"
                  disabled={submitting}
                  className="mt-3"
                />
              </div>

              <div className="rounded-xl border p-4">
                <div className="mb-3">
                  <p className="font-medium">Coach feedback layer</p>
                  <p className="text-sm text-muted-foreground">Invite coaches in the collaborator list to review this upload.</p>
                </div>
                <label className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={coachFeedbackMeta.enabled}
                    onChange={(event) => setCoachFeedbackMeta((current) => ({ ...current, enabled: event.target.checked }))}
                  />
                  Enable coach feedback requests
                </label>
                {coachFeedbackMeta.enabled ? (
                  <textarea
                    value={coachFeedbackMeta.prompt}
                    onChange={(event) => setCoachFeedbackMeta((current) => ({ ...current, prompt: event.target.value }))}
                    placeholder="What should coaches review in this clip?"
                    className="mt-3 min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                ) : null}
              </div>

              <div className="rounded-xl border p-4">
                <p className="mb-3 font-medium">Verified session</p>
                <label className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={verifiedSessionMeta.enabled}
                    onChange={(event) => setVerifiedSessionMeta((current) => ({ ...current, enabled: event.target.checked }))}
                  />
                  Mark this clip as recorded in a verified session
                </label>
                {verifiedSessionMeta.enabled ? (
                  <div className="mt-3 grid gap-3 md:grid-cols-2">
                    <Input value={verifiedSessionMeta.sessionType} onChange={(event) => setVerifiedSessionMeta((current) => ({ ...current, sessionType: event.target.value }))} placeholder="Session type: camp, game, workout" />
                    <Input value={verifiedSessionMeta.sessionLabel} onChange={(event) => setVerifiedSessionMeta((current) => ({ ...current, sessionLabel: event.target.value }))} placeholder="Session label" />
                    <Input value={verifiedSessionMeta.verifiedBy} onChange={(event) => setVerifiedSessionMeta((current) => ({ ...current, verifiedBy: event.target.value }))} placeholder="Verified by" className="md:col-span-2" />
                  </div>
                ) : null}
              </div>

              <div className="rounded-xl border p-4">
                <p className="mb-3 font-medium">Clip request upload</p>
                <div className="grid gap-3 md:grid-cols-2">
                  <Input value={clipRequestMeta.requestType} onChange={(event) => setClipRequestMeta((current) => ({ ...current, requestType: event.target.value }))} placeholder="Request type: coach, team, brand, recruiting" />
                  <Input value={clipRequestMeta.requesterId} onChange={(event) => setClipRequestMeta((current) => ({ ...current, requesterId: event.target.value }))} placeholder="Requester ID" />
                  <Input value={clipRequestMeta.requesterLabel} onChange={(event) => setClipRequestMeta((current) => ({ ...current, requesterLabel: event.target.value }))} placeholder="Requester label" />
                  <textarea value={clipRequestMeta.requestNote} onChange={(event) => setClipRequestMeta((current) => ({ ...current, requestNote: event.target.value }))} placeholder="Request note" className="min-h-20 rounded-md border border-input bg-background px-3 py-2 text-sm md:col-span-2" />
                </div>
              </div>

              <Input
                type="datetime-local"
                value={scheduledFor}
                onChange={(event) => setScheduledFor(event.target.value)}
                disabled={submitting}
              />
              {scheduledFor.trim() ? (
                <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-700">
                  This upload will stay off-feed until the scheduled time, then appear automatically.
                </div>
              ) : null}
              <div className="grid gap-3 md:grid-cols-2">
                <select value={visibility} onChange={(event) => setVisibility(event.target.value as "public" | "subscribers" | "premium_group")} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="public">Public</option>
                  <option value="subscribers">Subscribers only</option>
                  <option value="premium_group">Premium group only</option>
                </select>
                {visibility === "premium_group" ? (
                  <select value={premiumGroupId} onChange={(event) => setPremiumGroupId(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                    <option value="">Choose premium group</option>
                    {premiumGroups.map((group) => (
                      <option key={group.id} value={group.id}>{group.name}</option>
                    ))}
                  </select>
                ) : null}
              </div>
              <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                <input type="checkbox" checked={sponsored} onChange={(event) => setSponsored(event.target.checked)} />
                Mark as sponsored
              </label>
              {sponsored ? (
                <Input value={sponsorLabel} onChange={(event) => setSponsorLabel(event.target.value)} placeholder="Sponsor label" disabled={submitting} />
              ) : null}
              {composerMode === "advanced" ? (
                <div className="space-y-4 rounded-xl border p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="font-medium">Advanced options</p>
                      <p className="text-sm text-muted-foreground">Editing, accessibility, AI analysis, publishing controls, and creator workflows.</p>
                    </div>
                    <Button type="button" variant="outline" onClick={() => setShowCreatorTools((current) => !current)}>
                      {showCreatorTools ? "Hide creator tools" : "Open creator tools"}
                    </Button>
                  </div>
                  <div className="grid gap-3 md:grid-cols-2">
                    <Input value={clipStartSec} onChange={(event) => setClipStartSec(event.target.value)} placeholder="Clip start (seconds)" disabled={submitting} />
                    <Input value={clipEndSec} onChange={(event) => setClipEndSec(event.target.value)} placeholder="Clip end (seconds)" disabled={submitting} />
                  </div>
              <div className="grid gap-3 md:grid-cols-3">
                <Input value={trimFrameStart} onChange={(event) => setTrimFrameStart(event.target.value)} placeholder="Frame trim start" disabled={submitting} />
                <Input value={trimFrameEnd} onChange={(event) => setTrimFrameEnd(event.target.value)} placeholder="Frame trim end" disabled={submitting} />
                <select value={playbackSpeed} onChange={(event) => setPlaybackSpeed(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="0.5">0.5x slow motion</option>
                  <option value="1">1x normal</option>
                  <option value="1.25">1.25x</option>
                </select>
              </div>
              <Input value={highlightTags} onChange={(event) => setHighlightTags(event.target.value)} placeholder="Highlight tags by move: crossover, euro, block..." disabled={submitting} />
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <Input value={autoCaption} onChange={(event) => setAutoCaption(event.target.value)} placeholder="Auto-caption text" disabled={submitting} />
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setAutoCaption(`${sport || "Sport"} highlight: ${caption || files[0]?.name || "Uploaded clip"}`)}
                >
                  Generate Caption
                </Button>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("caption_rewrite")} disabled={assistantLoading !== null}>
                  {assistantLoading === "caption_rewrite" ? "Rewriting..." : "AI Rewrite Caption"}
                </Button>
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("hashtags")} disabled={assistantLoading !== null}>
                  {assistantLoading === "hashtags" ? "Suggesting..." : "AI Hashtags"}
                </Button>
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("translate")} disabled={assistantLoading !== null}>
                  {assistantLoading === "translate" ? "Translating..." : "Translate Caption"}
                </Button>
              </div>
              <textarea
                value={translatedCaption}
                onChange={(event) => setTranslatedCaption(event.target.value)}
                placeholder="Translated caption"
                disabled={submitting}
                className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
              <Input
                value={accessibilityLabel}
                onChange={(event) => setAccessibilityLabel(event.target.value)}
                placeholder="Screen-reader label for this media"
                disabled={submitting}
              />
              <textarea
                value={aiHighlightAnalysis}
                onChange={(event) => setAiHighlightAnalysis(event.target.value)}
                placeholder="AI highlight analysis"
                disabled={submitting}
                className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
              <Button
                type="button"
                variant="outline"
                onClick={async () => {
                  const response = await fetch("/api/highlight-analysis", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ caption, sport, contentType, autoCaption }),
                  });
                  const data = (await response.json()) as { analysis?: string };
                  setAiHighlightAnalysis(data.analysis || "No analysis returned.");
                }}
                >
                  Run AI Highlight Analysis
                </Button>
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <Input value={thumbnailHint} onChange={(event) => setThumbnailHint(event.target.value)} placeholder="Best thumbnail note" disabled={submitting} />
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("thumbnail")} disabled={assistantLoading !== null}>
                  {assistantLoading === "thumbnail" ? "Picking..." : "Best Thumbnail"}
                </Button>
              </div>
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <textarea
                  value={voiceoverScript}
                  onChange={(event) => setVoiceoverScript(event.target.value)}
                  placeholder="Voiceover script for this clip"
                  disabled={submitting}
                  className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                />
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("voiceover")} disabled={assistantLoading !== null}>
                  {assistantLoading === "voiceover" ? "Writing..." : "AI Voiceover"}
                </Button>
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <select value={musicSelection} onChange={(event) => setMusicSelection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Music library</option>
                  {(toolkitProfile?.musicLibrary ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.mood}</option>
                  ))}
                </select>
                <select value={introTemplate} onChange={(event) => setIntroTemplate(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Intro template</option>
                  {(toolkitProfile?.introTemplates ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.style}</option>
                  ))}
                </select>
                <select value={outroTemplate} onChange={(event) => setOutroTemplate(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Outro template</option>
                  {(toolkitProfile?.outroTemplates ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.style}</option>
                  ))}
                </select>
                <select value={overlaySelection} onChange={(event) => setOverlaySelection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Team-branded overlay</option>
                  {(toolkitProfile?.overlays ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.teamName}</option>
                  ))}
                </select>
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <Input value={beforeAfterLabel} onChange={(event) => setBeforeAfterLabel(event.target.value)} placeholder="Before/after training label" disabled={submitting} />
                <Input value={comparisonLabel} onChange={(event) => setComparisonLabel(event.target.value)} placeholder="Side-by-side comparison label" disabled={submitting} />
                <Input value={reactionChainLabel} onChange={(event) => setReactionChainLabel(event.target.value)} placeholder="Reaction video chain note" disabled={submitting} />
                <Input value={spotlightMoment} onChange={(event) => setSpotlightMoment(event.target.value)} placeholder="Spotlight best moment" disabled={submitting} />
                <Input value={playerOfWeekTitle} onChange={(event) => setPlayerOfWeekTitle(event.target.value)} placeholder="Player of the week template title" disabled={submitting} />
                <Input value={postingPlatform} onChange={(event) => setPostingPlatform(event.target.value)} placeholder="Best posting platform" disabled={submitting} />
              </div>
              <Input value={crossPostTargets} onChange={(event) => setCrossPostTargets(event.target.value)} placeholder="Cross-post export targets: Instagram, TikTok, YouTube..." disabled={submitting} />
              <div className="grid gap-3 md:grid-cols-3">
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={watermarkEnabled} onChange={(event) => setWatermarkEnabled(event.target.checked)} />
                  Watermark content
                </label>
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={downloadProtected} onChange={(event) => setDownloadProtected(event.target.checked)} />
                  Hide download controls
                </label>
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={rightClickProtected} onChange={(event) => setRightClickProtected(event.target.checked)} />
                  Block right click
                </label>
              </div>
              {remixPostId ? (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-muted-foreground">
                  Remixing post: {remixPostId}
                </div>
              ) : null}

              {showCreatorTools ? (
              <>
              <div className="rounded-xl border p-4">
                <p className="font-semibold">Creator Toolkit</p>
                <p className="mt-1 text-sm text-muted-foreground">Save reusable media assets, content calendar items, clip requests, collab invites, and recruiting highlight packs.</p>
                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Input value={calendarForm.title} onChange={(event) => setCalendarForm((current) => ({ ...current, title: event.target.value }))} placeholder="Content calendar title" />
                    <Input value={calendarForm.publishAt} onChange={(event) => setCalendarForm((current) => ({ ...current, publishAt: event.target.value }))} type="datetime-local" />
                    <Input value={calendarForm.platform} onChange={(event) => setCalendarForm((current) => ({ ...current, platform: event.target.value }))} placeholder="Platform" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          contentCalendar: [
                            ...(toolkitProfile?.contentCalendar ?? []),
                            { id: `calendar-${Date.now()}`, ...calendarForm },
                          ],
                        }).then(async () => {
                          setCalendarForm({ title: "", publishAt: "", platform: "HoopLink" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!calendarForm.title.trim()}
                    >
                      Save Content Calendar
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={collabInviteForm.creatorName} onChange={(event) => setCollabInviteForm((current) => ({ ...current, creatorName: event.target.value }))} placeholder="Collab creator" />
                    <Input value={collabInviteForm.brief} onChange={(event) => setCollabInviteForm((current) => ({ ...current, brief: event.target.value }))} placeholder="Collab brief" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          collaborationInvites: [
                            ...(toolkitProfile?.collaborationInvites ?? []),
                            { id: `collab-${Date.now()}`, creatorName: collabInviteForm.creatorName, brief: collabInviteForm.brief, status: "open" },
                          ],
                        }).then(async () => {
                          setCollabInviteForm({ creatorName: "", brief: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!collabInviteForm.creatorName.trim()}
                    >
                      Save Collaboration Invite
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={fanClipRequestForm.requester} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, requester: event.target.value }))} placeholder="Fan requester" />
                    <Input value={fanClipRequestForm.clipType} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, clipType: event.target.value }))} placeholder="Requested clip type" />
                    <Input value={fanClipRequestForm.note} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, note: event.target.value }))} placeholder="Request note" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          fanClipRequests: [
                            ...(toolkitProfile?.fanClipRequests ?? []),
                            { id: `fan-${Date.now()}`, ...fanClipRequestForm },
                          ],
                        }).then(async () => {
                          setFanClipRequestForm({ requester: "", clipType: "", note: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!fanClipRequestForm.requester.trim()}
                    >
                      Save Fan Clip Request
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={clipMarketForm.title} onChange={(event) => setClipMarketForm((current) => ({ ...current, title: event.target.value }))} placeholder="Marketplace listing" />
                    <Input value={clipMarketForm.priceLabel} onChange={(event) => setClipMarketForm((current) => ({ ...current, priceLabel: event.target.value }))} placeholder="Price label" />
                    <Input value={clipMarketForm.note} onChange={(event) => setClipMarketForm((current) => ({ ...current, note: event.target.value }))} placeholder="Listing note" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          clipMarketplace: [
                            ...(toolkitProfile?.clipMarketplace ?? []),
                            { id: `market-${Date.now()}`, ...clipMarketForm },
                          ],
                        }).then(async () => {
                          setClipMarketForm({ title: "", priceLabel: "", note: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!clipMarketForm.title.trim()}
                    >
                      Save Clip Marketplace Item
                    </Button>
                  </div>
                </div>

                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Input value={recruitingPackForm.title} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, title: event.target.value }))} placeholder="Recruiting pack title" />
                    <Input value={recruitingPackForm.audience} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, audience: event.target.value }))} placeholder="Audience" />
                    <Input value={recruitingPackForm.summary} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, summary: event.target.value }))} placeholder="Pack summary" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          recruitingPacks: [
                            ...(toolkitProfile?.recruitingPacks ?? []),
                            { id: `pack-${Date.now()}`, ...recruitingPackForm },
                          ],
                        }).then(async () => {
                          setRecruitingPackForm({ title: "", audience: "", summary: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!recruitingPackForm.title.trim()}
                    >
                      Save Recruiting Pack
                    </Button>
                  </div>
                  <div className="rounded-lg bg-muted p-3 text-sm">
                    <p className="font-medium">Creator guidance</p>
                    <p className="mt-2">Best posting time suggestion: aim for your next {contentType === "reel" ? "reel" : "post"} when your audience is most active, and use {postingPlatform || "HoopLink"} as the primary publish lane.</p>
                    <p className="mt-2">Auto resize targets: {crossPostTargets || "Add TikTok, Reels, Shorts, or X exports here."}</p>
                    <p className="mt-2">Thumbnail test: {thumbnailHint || "Save a thumbnail idea above to prepare A/B testing."}</p>
                  </div>
                </div>
              </div>

              <div className="rounded-xl border p-4">
                <p className="font-semibold">Full Creator Studio Suite</p>
                <p className="mt-1 text-sm text-muted-foreground">Track the rest of your creator workflow here: analytics, approvals, rights, packaging, portfolio, exports, monetization, and long-form production planning.</p>
                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  {ADVANCED_STUDIO_FIELDS.map(({ key, label }) => (
                    <div key={key} className="rounded-lg border p-3">
                      <p className="font-medium">{label}</p>
                      <textarea
                        value={advancedStudioMeta[key] ?? ""}
                        onChange={(event) => setAdvancedStudioMeta((current) => ({ ...current, [key]: event.target.value }))}
                        placeholder={`One ${label.toLowerCase()} item per line`}
                        className="mt-3 min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      />
                      <div className="mt-3 space-y-2">
                        {(toolkitProfile?.advancedStudioNotes?.[key] ?? []).slice(0, 3).map((item) => (
                          <div key={`${key}-${item}`} className="rounded-md bg-muted p-2 text-sm">{item}</div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 flex justify-end">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() =>
                      void saveCreatorToolkitProfile({
                        advancedStudioNotes: Object.fromEntries(
                          ADVANCED_STUDIO_FIELDS.map(({ key }) => [
                            key,
                            (advancedStudioMeta[key] ?? "")
                              .split("\n")
                              .map((value) => value.trim())
                              .filter(Boolean),
                          ]),
                        ),
                      }).then(async () => {
                        const nextProfile = await getCreatorToolkitProfile();
                        setToolkitProfile(nextProfile);
                        setAdvancedStudioMeta(
                          Object.fromEntries(
                            ADVANCED_STUDIO_FIELDS.map(({ key }) => [key, (nextProfile.advancedStudioNotes?.[key] ?? []).join("\n")]),
                          ),
                        );
                      })
                    }
                  >
                    Save Creator Studio
                  </Button>
                </div>
              </div>
              </>
              ) : null}
            </div>
              ) : null}

              {error ? <p className="text-sm text-destructive">{error}</p> : null}
              {publishStatus ? (
                <div className="rounded-xl border p-4">
                  <div className="mb-2 flex items-center justify-between text-sm">
                    <span>{publishStatus}</span>
                    <span>{publishProgress}%</span>
                  </div>
                  <div className="h-2 rounded-full bg-muted">
                    <div className="h-2 rounded-full bg-primary transition-all" style={{ width: `${publishProgress}%` }} />
                  </div>
                </div>
              ) : null}
              {failedFiles.length ? (
                <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">
                  <p className="font-medium text-destructive">Upload needs another try</p>
                  <p className="mt-1 text-muted-foreground">{failedFiles.join(", ")}</p>
                </div>
              ) : null}

              <div className="flex gap-3">
                <Button type="submit" disabled={submitting} className="flex-1">
                  {submitting ? "Publishing..." : contentType === "reel" ? "Publish reel" : "Publish post"}
                </Button>
                {failedFiles.length ? (
                  <Button type="submit" variant="outline" disabled={submitting}>
                    Retry
                  </Button>
                ) : null}
                <Button
                  type="button"
                  variant="outline"
                  onClick={() =>
                    void saveUploadDraft({
                      caption,
                      sport,
                      contentType,
                      previewType: mediaKind ?? "unknown",
                      postType,
                      questionPrompt,
                      pollOptions,
                      collaborators: selectedCollaboratorIds.length
                        ? selectedCollaboratorIds
                        : collaborators
                            .split(",")
                            .map((value) => value.trim())
                            .filter(Boolean),
                      remixPostId,
                      scheduledFor,
                      visibility,
                      premiumGroupId,
                      sponsored,
                      sponsorLabel,
                      autoCaption,
                      translatedCaption,
                      accessibilityLabel,
                      aiHighlightAnalysis,
                      voiceoverScript,
                      thumbnailHint,
                      clipStartSec: clipStartSec ? Number(clipStartSec) : undefined,
                      clipEndSec: clipEndSec ? Number(clipEndSec) : undefined,
                      watermarkEnabled,
                      downloadProtected,
                      rightClickProtected,
                    }).then(() => router.push("/drafts"))
                  }
                >
                  Save Draft
                </Button>
                <Button type="button" variant="outline" asChild>
                  <Link href={contentType === "reel" ? "/reels" : "/feed"}>Cancel</Link>
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </ProtectedRoute>
  );
}

export default function UploadPage() {
  return (
    <AuthProvider>
      <Suspense fallback={null}>
        <UploadPageContent />
      </Suspense>
    </AuthProvider>
  );
}
