"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Film, Image as ImageIcon, UploadCloud, Video } from "lucide-react";

import { AuthProvider, useAuthContext } from "@/components/AuthProvider";
import ProtectedRoute from "@/components/ProtectedRoute";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getOwnedPremiumGroups, type PremiumGroupRecord } from "@/lib/creator-hub";
import { deleteUploadDraft, getUploadDrafts, saveUploadDraft } from "@/lib/drafts";
import { getCreatorToolkitProfile, saveCreatorToolkitProfile, type CreatorToolkitProfile } from "@/lib/media-lab";
import { createPost, getCurrentUserSport } from "@/lib/posts";

const ADVANCED_STUDIO_FIELDS = [
  { key: "sceneDetection", label: "Scene detection" },
  { key: "motionTracking", label: "Motion tracking" },
  { key: "captionStyling", label: "Caption styling" },
  { key: "multiAngleSync", label: "Multi-angle sync" },
  { key: "shotMapOverlay", label: "Shot-map overlay" },
  { key: "statOverlays", label: "Stat overlays" },
  { key: "teamLogoOverlays", label: "Team logo overlays" },
  { key: "ctaOverlays", label: "CTA overlays" },
  { key: "calloutStickers", label: "Callout stickers" },
  { key: "chapterMarkers", label: "Chapter markers" },
  { key: "videoPlaylists", label: "Video playlists" },
  { key: "highlightCollections", label: "Highlight collections" },
  { key: "seasonMixtapes", label: "Season mixtapes" },
  { key: "weeklyRecapBuilder", label: "Weekly recap builder" },
  { key: "creatorRevenueOverlays", label: "Creator revenue overlays" },
  { key: "audioCleanup", label: "Audio cleanup" },
  { key: "noiseReduction", label: "Noise reduction" },
  { key: "autoZoomOnAction", label: "Auto zoom on action" },
  { key: "smartCropForMobile", label: "Smart crop for mobile" },
  { key: "clipLengthOptimizer", label: "Clip length optimizer" },
  { key: "hookSuggestionAi", label: "Hook suggestion AI" },
  { key: "thumbnailTextAi", label: "Thumbnail text AI" },
  { key: "captionAbTesting", label: "Caption A/B testing" },
  { key: "watchTimeAnalytics", label: "Watch-time analytics" },
  { key: "completionRateAnalytics", label: "Completion-rate analytics" },
  { key: "shareRateAnalytics", label: "Share-rate analytics" },
  { key: "saveRateAnalytics", label: "Save-rate analytics" },
  { key: "sponsorClickTracking", label: "Sponsor click-through tracking" },
  { key: "creatorCrmBrands", label: "Creator CRM for brands" },
  { key: "publishingQueue", label: "Publishing queue" },
  { key: "draftReviewWorkflows", label: "Draft review workflows" },
  { key: "brandApprovalFlow", label: "Brand approval flow" },
  { key: "teamMediaApproval", label: "Team media approval" },
  { key: "videoRightsTracker", label: "Video rights tracker" },
  { key: "usageLicensingTracker", label: "Usage licensing tracker" },
  { key: "clipRequestTickets", label: "Clip request tickets" },
  { key: "highlightRequestRouting", label: "Highlight request routing" },
  { key: "fanSubmittedMoments", label: "Fan-submitted moments" },
  { key: "autoGeneratedReels", label: "Auto-generated reels" },
  { key: "shortFormPresets", label: "Short-form export presets" },
  { key: "longFormPresets", label: "Long-form export presets" },
  { key: "socialCoverGenerator", label: "Social cover generator" },
  { key: "promoTrailerBuilder", label: "Promo trailer builder" },
  { key: "trainingMontageBuilder", label: "Training montage builder" },
  { key: "recruitingMontageBuilder", label: "Recruiting montage builder" },
  { key: "sponsorshipMontageBuilder", label: "Sponsorship montage builder" },
  { key: "playerIntroTemplates", label: "Player intro templates" },
  { key: "teamIntroTemplates", label: "Team intro templates" },
  { key: "documentaryTimelines", label: "Documentary timelines" },
  { key: "creatorPortfolioPage", label: "Creator portfolio page" },
  { key: "contentBacklogBoard", label: "Content backlog board" },
  { key: "projectFolders", label: "Project folders" },
  { key: "versionHistory", label: "Version history" },
  { key: "timelineReviewComments", label: "Comment-on-timeline review" },
  { key: "timestampedCoachNotes", label: "Timestamped coach notes" },
  { key: "videoScriptDrafts", label: "Video script drafts" },
  { key: "storyboardBuilder", label: "Storyboard builder" },
  { key: "sceneLabels", label: "Scene labels" },
  { key: "cloudStorageExport", label: "Export to cloud storage" },
  { key: "downloadPermissions", label: "Download permissions" },
  { key: "fanRemixPermissions", label: "Fan remix permissions" },
  { key: "paidVideoPacks", label: "Paid video packs" },
  { key: "subscribersOnlyVideos", label: "Subscribers-only videos" },
  { key: "teamPrivateVideos", label: "Team-private videos" },
  { key: "watermarkedPreviews", label: "Watermarked previews" },
  { key: "leadCaptureOnMedia", label: "Lead capture on media" },
  { key: "productTagsInVideo", label: "Product tags in video" },
  { key: "bookingCtaInVideo", label: "Booking CTA in video" },
] as const;

function UploadPageContent() {
  const { user, loading } = useAuthContext();
  const router = useRouter();
  const searchParams = useSearchParams();
  const [caption, setCaption] = useState("");
  const [sport, setSport] = useState("");
  const [contentType, setContentType] = useState<"post" | "reel">("post");
  const [postType, setPostType] = useState<"standard" | "poll" | "qa">("standard");
  const [questionPrompt, setQuestionPrompt] = useState("");
  const [pollOptions, setPollOptions] = useState(["", ""]);
  const [collaborators, setCollaborators] = useState("");
  const [scheduledFor, setScheduledFor] = useState("");
  const [remixPostId, setRemixPostId] = useState("");
  const [visibility, setVisibility] = useState<"public" | "subscribers" | "premium_group">("public");
  const [premiumGroupId, setPremiumGroupId] = useState("");
  const [sponsored, setSponsored] = useState(false);
  const [sponsorLabel, setSponsorLabel] = useState("");
  const [autoCaption, setAutoCaption] = useState("");
  const [translatedCaption, setTranslatedCaption] = useState("");
  const [accessibilityLabel, setAccessibilityLabel] = useState("");
  const [aiHighlightAnalysis, setAiHighlightAnalysis] = useState("");
  const [voiceoverScript, setVoiceoverScript] = useState("");
  const [thumbnailHint, setThumbnailHint] = useState("");
  const [clipStartSec, setClipStartSec] = useState("");
  const [clipEndSec, setClipEndSec] = useState("");
  const [watermarkEnabled, setWatermarkEnabled] = useState(false);
  const [downloadProtected, setDownloadProtected] = useState(false);
  const [rightClickProtected, setRightClickProtected] = useState(false);
  const [premiumGroups, setPremiumGroups] = useState<PremiumGroupRecord[]>([]);
  const [toolkitProfile, setToolkitProfile] = useState<CreatorToolkitProfile | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [assistantLoading, setAssistantLoading] = useState<string | null>(null);
  const [profileLoading, setProfileLoading] = useState(true);
  const [loadedDraftId, setLoadedDraftId] = useState<string | null>(null);
  const [playbackSpeed, setPlaybackSpeed] = useState("1");
  const [trimFrameStart, setTrimFrameStart] = useState("0");
  const [trimFrameEnd, setTrimFrameEnd] = useState("");
  const [highlightTags, setHighlightTags] = useState("");
  const [musicSelection, setMusicSelection] = useState("");
  const [introTemplate, setIntroTemplate] = useState("");
  const [outroTemplate, setOutroTemplate] = useState("");
  const [overlaySelection, setOverlaySelection] = useState("");
  const [beforeAfterLabel, setBeforeAfterLabel] = useState("");
  const [comparisonLabel, setComparisonLabel] = useState("");
  const [reactionChainLabel, setReactionChainLabel] = useState("");
  const [spotlightMoment, setSpotlightMoment] = useState("");
  const [playerOfWeekTitle, setPlayerOfWeekTitle] = useState("");
  const [postingPlatform, setPostingPlatform] = useState("HoopLink");
  const [crossPostTargets, setCrossPostTargets] = useState("");
  const [collabInviteForm, setCollabInviteForm] = useState({ creatorName: "", brief: "" });
  const [fanClipRequestForm, setFanClipRequestForm] = useState({ requester: "", clipType: "", note: "" });
  const [clipMarketForm, setClipMarketForm] = useState({ title: "", priceLabel: "", note: "" });
  const [recruitingPackForm, setRecruitingPackForm] = useState({ title: "", audience: "", summary: "" });
  const [calendarForm, setCalendarForm] = useState({ title: "", publishAt: "", platform: "HoopLink" });
  const [advancedStudioMeta, setAdvancedStudioMeta] = useState<Record<string, string>>({});

  useEffect(() => {
    if (!user) {
      setProfileLoading(false);
      return;
    }

    getCurrentUserSport()
      .then((savedSport) => {
        if (savedSport) {
          setSport(savedSport);
        }
      })
      .then(() => getOwnedPremiumGroups())
      .then(setPremiumGroups)
      .then(() => getCreatorToolkitProfile())
      .then((profile) => {
        setToolkitProfile(profile);
        setAdvancedStudioMeta(
          Object.fromEntries(
            ADVANCED_STUDIO_FIELDS.map(({ key }) => [key, (profile.advancedStudioNotes?.[key] ?? []).join("\n")]),
          ),
        );
      })
      .finally(() => setProfileLoading(false));
  }, [user]);

  useEffect(() => {
    if (!file) {
      setPreviewUrl("");
      return;
    }

    const nextPreviewUrl = URL.createObjectURL(file);
    setPreviewUrl(nextPreviewUrl);

    return () => {
      URL.revokeObjectURL(nextPreviewUrl);
    };
  }, [file]);

  useEffect(() => {
    const draftId = searchParams.get("draft");
    const initialCaption = searchParams.get("caption");
    const remixId = searchParams.get("remix");
    const typeParam = searchParams.get("type");
    const templateParam = searchParams.get("template");

    if (typeParam === "poll" || typeParam === "qa") {
      setPostType(typeParam);
    }

    if (templateParam === "poll") {
      setCaption((current) => current || "What do you think? #poll");
      setPollOptions((current) => current.length >= 2 ? current : ["Option 1", "Option 2"]);
    }

    if (templateParam === "qa") {
      setQuestionPrompt((current) => current || "Ask your community something specific.");
      setCaption((current) => current || "Drop your answer below. #qa");
    }

    if (initialCaption && !caption) {
      setCaption(initialCaption);
    }
    if (remixId && !remixPostId) {
      setRemixPostId(remixId);
      setCaption((current) => current || `Remix on @creator #remix`);
    }
    if (!draftId || loadedDraftId === draftId) {
      return;
    }

    getUploadDrafts().then((drafts) => {
      const draft = drafts.find((item: { id: string }) => item.id === draftId);
      if (!draft) {
        return;
      }

      setCaption(draft.caption);
      setSport(draft.sport);
      setContentType(draft.contentType);
      setPostType(draft.postType ?? "standard");
      setQuestionPrompt(draft.questionPrompt ?? "");
      setPollOptions(draft.pollOptions?.length ? draft.pollOptions : ["", ""]);
      setCollaborators((draft.collaborators ?? []).join(", "));
      setScheduledFor(draft.scheduledFor ?? "");
      setRemixPostId(draft.remixPostId ?? "");
      setVisibility(draft.visibility ?? "public");
      setPremiumGroupId(draft.premiumGroupId ?? "");
      setSponsored(Boolean(draft.sponsored));
      setSponsorLabel(draft.sponsorLabel ?? "");
      setAutoCaption(draft.autoCaption ?? "");
      setTranslatedCaption(draft.translatedCaption ?? "");
      setAccessibilityLabel(draft.accessibilityLabel ?? "");
      setAiHighlightAnalysis(draft.aiHighlightAnalysis ?? "");
      setVoiceoverScript(draft.voiceoverScript ?? "");
      setThumbnailHint(draft.thumbnailHint ?? "");
      setClipStartSec(draft.clipStartSec ? String(draft.clipStartSec) : "");
      setClipEndSec(draft.clipEndSec ? String(draft.clipEndSec) : "");
      setWatermarkEnabled(Boolean(draft.watermarkEnabled));
      setDownloadProtected(Boolean(draft.downloadProtected));
      setRightClickProtected(Boolean(draft.rightClickProtected));
      setLoadedDraftId(draft.id);
    });
  }, [caption, loadedDraftId, remixPostId, searchParams]);

  const mediaKind = useMemo(() => {
    if (!file) return null;
    return file.type.startsWith("video/") ? "video" : "image";
  }, [file]);

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextFile = event.target.files?.[0] ?? null;
    setError("");
    setFile(nextFile);
  };

  const runMediaAssist = async (task: "caption_rewrite" | "hashtags" | "translate" | "voiceover" | "thumbnail") => {
    setAssistantLoading(task);
    setError("");
    try {
      const response = await fetch("/api/media-assist", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          task,
          caption,
          sport,
          autoCaption,
          targetLanguage: "Spanish",
        }),
      });
      const data = (await response.json()) as { result?: string; error?: string };
      if (!response.ok) {
        throw new Error(data.error || "Media assist request failed.");
      }
      const result = data.result || "";
      if (task === "caption_rewrite") {
        setCaption(result);
      } else if (task === "hashtags") {
        setCaption((current) => [current.trim(), result.trim()].filter(Boolean).join(" "));
      } else if (task === "translate") {
        setTranslatedCaption(result);
      } else if (task === "voiceover") {
        setVoiceoverScript(result);
      } else if (task === "thumbnail") {
        setThumbnailHint(result);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Media assist failed.");
    } finally {
      setAssistantLoading(null);
    }
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError("");

    if (contentType === "reel" && !file) {
      setError("Choose a video to upload.");
      return;
    }

    if (contentType === "reel" && file && !file.type.startsWith("video/")) {
      setError("Reels must use a video file.");
      return;
    }

    if (postType === "poll" && pollOptions.filter((option) => option.trim()).length < 2) {
      setError("Add at least two poll options.");
      return;
    }

    setSubmitting(true);

    try {
      await createPost({
        caption,
        sport,
        file,
        contentType,
        postType,
        questionPrompt,
        pollOptions,
        collaborators: collaborators
          .split(",")
          .map((value) => value.trim())
          .filter(Boolean),
        remixPostId,
        scheduledFor,
        visibility,
        premiumGroupId,
        sponsored,
        sponsorLabel,
        autoCaption,
        translatedCaption,
        accessibilityLabel,
        aiHighlightAnalysis,
        voiceoverScript,
        thumbnailHint,
        clipStartSec: clipStartSec ? Number(clipStartSec) : undefined,
        clipEndSec: clipEndSec ? Number(clipEndSec) : undefined,
        watermarkEnabled,
        downloadProtected,
        rightClickProtected,
      });
      if (loadedDraftId) {
        await deleteUploadDraft(loadedDraftId);
      }
      router.push(contentType === "reel" ? "/reels" : "/feed");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Your upload could not be published.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading || profileLoading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="h-10 w-10 animate-spin rounded-full border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <ProtectedRoute>
      <div className="mx-auto max-w-2xl py-8">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <UploadCloud className="h-5 w-5 text-primary" />
              Create content
            </CardTitle>
            <CardDescription>
              Publish a standard post or a reel using the same media pipeline.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form className="space-y-5" onSubmit={handleSubmit}>
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setContentType("post")}
                  className={`rounded-xl border p-4 text-left ${contentType === "post" ? "border-primary bg-primary/5" : ""}`}
                >
                  <ImageIcon className="mb-2 h-5 w-5 text-primary" />
                  <p className="font-semibold">Post</p>
                  <p className="text-sm text-muted-foreground">Photos or videos in the main feed.</p>
                </button>
                <button
                  type="button"
                  onClick={() => setContentType("reel")}
                  className={`rounded-xl border p-4 text-left ${contentType === "reel" ? "border-primary bg-primary/5" : ""}`}
                >
                  <Film className="mb-2 h-5 w-5 text-primary" />
                  <p className="font-semibold">Reel</p>
                  <p className="text-sm text-muted-foreground">Vertical video for the reels feed.</p>
                </button>
              </div>

              {contentType === "post" ? (
                <div className="grid grid-cols-3 gap-3">
                  {([
                    { value: "standard", label: "Standard", hint: "Normal post" },
                    { value: "poll", label: "Poll", hint: "Collect votes" },
                    { value: "qa", label: "Q&A", hint: "Ask the community" },
                  ] as const).map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => setPostType(option.value)}
                      className={`rounded-xl border p-4 text-left ${postType === option.value ? "border-primary bg-primary/5" : ""}`}
                    >
                      <p className="font-semibold">{option.label}</p>
                      <p className="text-sm text-muted-foreground">{option.hint}</p>
                    </button>
                  ))}
                </div>
              ) : null}

              <Input
                type="file"
                accept={contentType === "reel" ? "video/*" : "image/*,video/*"}
                onChange={handleFileChange}
                disabled={submitting}
              />

              {previewUrl ? (
                <div className="overflow-hidden rounded-xl border bg-muted">
                  {mediaKind === "video" ? (
                    <video src={previewUrl} controls className="max-h-[420px] w-full bg-black object-cover" />
                  ) : (
                    <img src={previewUrl} alt="Upload preview" className="max-h-[420px] w-full object-cover" />
                  )}
                </div>
              ) : (
                <div className="rounded-xl border border-dashed p-8 text-center">
                  {contentType === "reel" ? (
                    <Video className="mx-auto mb-3 h-10 w-10 text-muted-foreground" />
                  ) : (
                    <ImageIcon className="mx-auto mb-3 h-10 w-10 text-muted-foreground" />
                  )}
                  <p className="font-medium">
                    {contentType === "reel" ? "Choose a video for your reel." : "Choose media for your post."}
                  </p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Use hashtags in the caption like `#basketball` to appear in topic feeds.
                  </p>
                </div>
              )}

              {postType === "qa" && contentType === "post" ? (
                <Input
                  value={questionPrompt}
                  onChange={(event) => setQuestionPrompt(event.target.value)}
                  placeholder="Ask a question to the community"
                  disabled={submitting}
                />
              ) : null}

              {postType === "poll" && contentType === "post" ? (
                <div className="space-y-3 rounded-xl border p-4">
                  <p className="text-sm font-medium">Poll Options</p>
                  {pollOptions.map((option, index) => (
                    <Input
                      key={index}
                      value={option}
                      onChange={(event) =>
                        setPollOptions((current) =>
                          current.map((currentOption, currentIndex) =>
                            currentIndex === index ? event.target.value : currentOption
                          )
                        )
                      }
                      placeholder={`Option ${index + 1}`}
                    />
                  ))}
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setPollOptions((current) => [...current, ""])}
                  >
                    Add Option
                  </Button>
                </div>
              ) : null}

              <Input value={sport} onChange={(event) => setSport(event.target.value)} placeholder="Sport" disabled={submitting} />

              <textarea
                value={caption}
                onChange={(event) => setCaption(event.target.value)}
                placeholder="What happened here? Add #tags so people can discover it."
                disabled={submitting}
                className="min-h-28 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />

              <Input
                value={collaborators}
                onChange={(event) => setCollaborators(event.target.value)}
                placeholder="Collaboration tags, comma separated usernames"
                disabled={submitting}
              />

              <Input
                type="datetime-local"
                value={scheduledFor}
                onChange={(event) => setScheduledFor(event.target.value)}
                disabled={submitting}
              />
              <div className="grid gap-3 md:grid-cols-2">
                <select value={visibility} onChange={(event) => setVisibility(event.target.value as "public" | "subscribers" | "premium_group")} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="public">Public</option>
                  <option value="subscribers">Subscribers only</option>
                  <option value="premium_group">Premium group only</option>
                </select>
                {visibility === "premium_group" ? (
                  <select value={premiumGroupId} onChange={(event) => setPremiumGroupId(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                    <option value="">Choose premium group</option>
                    {premiumGroups.map((group) => (
                      <option key={group.id} value={group.id}>{group.name}</option>
                    ))}
                  </select>
                ) : null}
              </div>
              <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                <input type="checkbox" checked={sponsored} onChange={(event) => setSponsored(event.target.checked)} />
                Mark as sponsored
              </label>
              {sponsored ? (
                <Input value={sponsorLabel} onChange={(event) => setSponsorLabel(event.target.value)} placeholder="Sponsor label" disabled={submitting} />
              ) : null}
              <div className="grid gap-3 md:grid-cols-2">
                <Input value={clipStartSec} onChange={(event) => setClipStartSec(event.target.value)} placeholder="Clip start (seconds)" disabled={submitting} />
                <Input value={clipEndSec} onChange={(event) => setClipEndSec(event.target.value)} placeholder="Clip end (seconds)" disabled={submitting} />
              </div>
              <div className="grid gap-3 md:grid-cols-3">
                <Input value={trimFrameStart} onChange={(event) => setTrimFrameStart(event.target.value)} placeholder="Frame trim start" disabled={submitting} />
                <Input value={trimFrameEnd} onChange={(event) => setTrimFrameEnd(event.target.value)} placeholder="Frame trim end" disabled={submitting} />
                <select value={playbackSpeed} onChange={(event) => setPlaybackSpeed(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="0.5">0.5x slow motion</option>
                  <option value="1">1x normal</option>
                  <option value="1.25">1.25x</option>
                </select>
              </div>
              <Input value={highlightTags} onChange={(event) => setHighlightTags(event.target.value)} placeholder="Highlight tags by move: crossover, euro, block..." disabled={submitting} />
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <Input value={autoCaption} onChange={(event) => setAutoCaption(event.target.value)} placeholder="Auto-caption text" disabled={submitting} />
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setAutoCaption(`${sport || "Sport"} highlight: ${caption || file?.name || "Uploaded clip"}`)}
                >
                  Generate Caption
                </Button>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("caption_rewrite")} disabled={assistantLoading !== null}>
                  {assistantLoading === "caption_rewrite" ? "Rewriting..." : "AI Rewrite Caption"}
                </Button>
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("hashtags")} disabled={assistantLoading !== null}>
                  {assistantLoading === "hashtags" ? "Suggesting..." : "AI Hashtags"}
                </Button>
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("translate")} disabled={assistantLoading !== null}>
                  {assistantLoading === "translate" ? "Translating..." : "Translate Caption"}
                </Button>
              </div>
              <textarea
                value={translatedCaption}
                onChange={(event) => setTranslatedCaption(event.target.value)}
                placeholder="Translated caption"
                disabled={submitting}
                className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
              <Input
                value={accessibilityLabel}
                onChange={(event) => setAccessibilityLabel(event.target.value)}
                placeholder="Screen-reader label for this media"
                disabled={submitting}
              />
              <textarea
                value={aiHighlightAnalysis}
                onChange={(event) => setAiHighlightAnalysis(event.target.value)}
                placeholder="AI highlight analysis"
                disabled={submitting}
                className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
              <Button
                type="button"
                variant="outline"
                onClick={async () => {
                  const response = await fetch("/api/highlight-analysis", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ caption, sport, contentType, autoCaption }),
                  });
                  const data = (await response.json()) as { analysis?: string };
                  setAiHighlightAnalysis(data.analysis || "No analysis returned.");
                }}
                >
                  Run AI Highlight Analysis
                </Button>
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <Input value={thumbnailHint} onChange={(event) => setThumbnailHint(event.target.value)} placeholder="Best thumbnail note" disabled={submitting} />
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("thumbnail")} disabled={assistantLoading !== null}>
                  {assistantLoading === "thumbnail" ? "Picking..." : "Best Thumbnail"}
                </Button>
              </div>
              <div className="grid gap-3 md:grid-cols-[1fr,auto]">
                <textarea
                  value={voiceoverScript}
                  onChange={(event) => setVoiceoverScript(event.target.value)}
                  placeholder="Voiceover script for this clip"
                  disabled={submitting}
                  className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                />
                <Button type="button" variant="outline" onClick={() => void runMediaAssist("voiceover")} disabled={assistantLoading !== null}>
                  {assistantLoading === "voiceover" ? "Writing..." : "AI Voiceover"}
                </Button>
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <select value={musicSelection} onChange={(event) => setMusicSelection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Music library</option>
                  {(toolkitProfile?.musicLibrary ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.mood}</option>
                  ))}
                </select>
                <select value={introTemplate} onChange={(event) => setIntroTemplate(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Intro template</option>
                  {(toolkitProfile?.introTemplates ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.style}</option>
                  ))}
                </select>
                <select value={outroTemplate} onChange={(event) => setOutroTemplate(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Outro template</option>
                  {(toolkitProfile?.outroTemplates ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.style}</option>
                  ))}
                </select>
                <select value={overlaySelection} onChange={(event) => setOverlaySelection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="">Team-branded overlay</option>
                  {(toolkitProfile?.overlays ?? []).map((item) => (
                    <option key={item.id} value={item.title}>{item.title} | {item.teamName}</option>
                  ))}
                </select>
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <Input value={beforeAfterLabel} onChange={(event) => setBeforeAfterLabel(event.target.value)} placeholder="Before/after training label" disabled={submitting} />
                <Input value={comparisonLabel} onChange={(event) => setComparisonLabel(event.target.value)} placeholder="Side-by-side comparison label" disabled={submitting} />
                <Input value={reactionChainLabel} onChange={(event) => setReactionChainLabel(event.target.value)} placeholder="Reaction video chain note" disabled={submitting} />
                <Input value={spotlightMoment} onChange={(event) => setSpotlightMoment(event.target.value)} placeholder="Spotlight best moment" disabled={submitting} />
                <Input value={playerOfWeekTitle} onChange={(event) => setPlayerOfWeekTitle(event.target.value)} placeholder="Player of the week template title" disabled={submitting} />
                <Input value={postingPlatform} onChange={(event) => setPostingPlatform(event.target.value)} placeholder="Best posting platform" disabled={submitting} />
              </div>
              <Input value={crossPostTargets} onChange={(event) => setCrossPostTargets(event.target.value)} placeholder="Cross-post export targets: Instagram, TikTok, YouTube..." disabled={submitting} />
              <div className="grid gap-3 md:grid-cols-3">
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={watermarkEnabled} onChange={(event) => setWatermarkEnabled(event.target.checked)} />
                  Watermark content
                </label>
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={downloadProtected} onChange={(event) => setDownloadProtected(event.target.checked)} />
                  Hide download controls
                </label>
                <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm">
                  <input type="checkbox" checked={rightClickProtected} onChange={(event) => setRightClickProtected(event.target.checked)} />
                  Block right click
                </label>
              </div>
              {remixPostId ? (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-muted-foreground">
                  Remixing post: {remixPostId}
                </div>
              ) : null}

              <div className="rounded-xl border p-4">
                <p className="font-semibold">Creator Toolkit</p>
                <p className="mt-1 text-sm text-muted-foreground">Save reusable media assets, content calendar items, clip requests, collab invites, and recruiting highlight packs.</p>
                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Input value={calendarForm.title} onChange={(event) => setCalendarForm((current) => ({ ...current, title: event.target.value }))} placeholder="Content calendar title" />
                    <Input value={calendarForm.publishAt} onChange={(event) => setCalendarForm((current) => ({ ...current, publishAt: event.target.value }))} type="datetime-local" />
                    <Input value={calendarForm.platform} onChange={(event) => setCalendarForm((current) => ({ ...current, platform: event.target.value }))} placeholder="Platform" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          contentCalendar: [
                            ...(toolkitProfile?.contentCalendar ?? []),
                            { id: `calendar-${Date.now()}`, ...calendarForm },
                          ],
                        }).then(async () => {
                          setCalendarForm({ title: "", publishAt: "", platform: "HoopLink" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!calendarForm.title.trim()}
                    >
                      Save Content Calendar
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={collabInviteForm.creatorName} onChange={(event) => setCollabInviteForm((current) => ({ ...current, creatorName: event.target.value }))} placeholder="Collab creator" />
                    <Input value={collabInviteForm.brief} onChange={(event) => setCollabInviteForm((current) => ({ ...current, brief: event.target.value }))} placeholder="Collab brief" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          collaborationInvites: [
                            ...(toolkitProfile?.collaborationInvites ?? []),
                            { id: `collab-${Date.now()}`, creatorName: collabInviteForm.creatorName, brief: collabInviteForm.brief, status: "open" },
                          ],
                        }).then(async () => {
                          setCollabInviteForm({ creatorName: "", brief: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!collabInviteForm.creatorName.trim()}
                    >
                      Save Collaboration Invite
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={fanClipRequestForm.requester} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, requester: event.target.value }))} placeholder="Fan requester" />
                    <Input value={fanClipRequestForm.clipType} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, clipType: event.target.value }))} placeholder="Requested clip type" />
                    <Input value={fanClipRequestForm.note} onChange={(event) => setFanClipRequestForm((current) => ({ ...current, note: event.target.value }))} placeholder="Request note" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          fanClipRequests: [
                            ...(toolkitProfile?.fanClipRequests ?? []),
                            { id: `fan-${Date.now()}`, ...fanClipRequestForm },
                          ],
                        }).then(async () => {
                          setFanClipRequestForm({ requester: "", clipType: "", note: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!fanClipRequestForm.requester.trim()}
                    >
                      Save Fan Clip Request
                    </Button>
                  </div>

                  <div className="space-y-2">
                    <Input value={clipMarketForm.title} onChange={(event) => setClipMarketForm((current) => ({ ...current, title: event.target.value }))} placeholder="Marketplace listing" />
                    <Input value={clipMarketForm.priceLabel} onChange={(event) => setClipMarketForm((current) => ({ ...current, priceLabel: event.target.value }))} placeholder="Price label" />
                    <Input value={clipMarketForm.note} onChange={(event) => setClipMarketForm((current) => ({ ...current, note: event.target.value }))} placeholder="Listing note" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          clipMarketplace: [
                            ...(toolkitProfile?.clipMarketplace ?? []),
                            { id: `market-${Date.now()}`, ...clipMarketForm },
                          ],
                        }).then(async () => {
                          setClipMarketForm({ title: "", priceLabel: "", note: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!clipMarketForm.title.trim()}
                    >
                      Save Clip Marketplace Item
                    </Button>
                  </div>
                </div>

                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Input value={recruitingPackForm.title} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, title: event.target.value }))} placeholder="Recruiting pack title" />
                    <Input value={recruitingPackForm.audience} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, audience: event.target.value }))} placeholder="Audience" />
                    <Input value={recruitingPackForm.summary} onChange={(event) => setRecruitingPackForm((current) => ({ ...current, summary: event.target.value }))} placeholder="Pack summary" />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        void saveCreatorToolkitProfile({
                          recruitingPacks: [
                            ...(toolkitProfile?.recruitingPacks ?? []),
                            { id: `pack-${Date.now()}`, ...recruitingPackForm },
                          ],
                        }).then(async () => {
                          setRecruitingPackForm({ title: "", audience: "", summary: "" });
                          const nextProfile = await getCreatorToolkitProfile();
                          setToolkitProfile(nextProfile);
                        })
                      }
                      disabled={!recruitingPackForm.title.trim()}
                    >
                      Save Recruiting Pack
                    </Button>
                  </div>
                  <div className="rounded-lg bg-muted p-3 text-sm">
                    <p className="font-medium">Creator guidance</p>
                    <p className="mt-2">Best posting time suggestion: aim for your next {contentType === "reel" ? "reel" : "post"} when your audience is most active, and use {postingPlatform || "HoopLink"} as the primary publish lane.</p>
                    <p className="mt-2">Auto resize targets: {crossPostTargets || "Add TikTok, Reels, Shorts, or X exports here."}</p>
                    <p className="mt-2">Thumbnail test: {thumbnailHint || "Save a thumbnail idea above to prepare A/B testing."}</p>
                  </div>
                </div>
              </div>

              <div className="rounded-xl border p-4">
                <p className="font-semibold">Full Creator Studio Suite</p>
                <p className="mt-1 text-sm text-muted-foreground">Track the rest of your creator workflow here: analytics, approvals, rights, packaging, portfolio, exports, monetization, and long-form production planning.</p>
                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  {ADVANCED_STUDIO_FIELDS.map(({ key, label }) => (
                    <div key={key} className="rounded-lg border p-3">
                      <p className="font-medium">{label}</p>
                      <textarea
                        value={advancedStudioMeta[key] ?? ""}
                        onChange={(event) => setAdvancedStudioMeta((current) => ({ ...current, [key]: event.target.value }))}
                        placeholder={`One ${label.toLowerCase()} item per line`}
                        className="mt-3 min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      />
                      <div className="mt-3 space-y-2">
                        {(toolkitProfile?.advancedStudioNotes?.[key] ?? []).slice(0, 3).map((item) => (
                          <div key={`${key}-${item}`} className="rounded-md bg-muted p-2 text-sm">{item}</div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 flex justify-end">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() =>
                      void saveCreatorToolkitProfile({
                        advancedStudioNotes: Object.fromEntries(
                          ADVANCED_STUDIO_FIELDS.map(({ key }) => [
                            key,
                            (advancedStudioMeta[key] ?? "")
                              .split("\n")
                              .map((value) => value.trim())
                              .filter(Boolean),
                          ]),
                        ),
                      }).then(async () => {
                        const nextProfile = await getCreatorToolkitProfile();
                        setToolkitProfile(nextProfile);
                        setAdvancedStudioMeta(
                          Object.fromEntries(
                            ADVANCED_STUDIO_FIELDS.map(({ key }) => [key, (nextProfile.advancedStudioNotes?.[key] ?? []).join("\n")]),
                          ),
                        );
                      })
                    }
                  >
                    Save Creator Studio
                  </Button>
                </div>
              </div>

              {error ? <p className="text-sm text-destructive">{error}</p> : null}

              <div className="flex gap-3">
                <Button type="submit" disabled={submitting} className="flex-1">
                  {submitting ? "Publishing..." : contentType === "reel" ? "Publish reel" : "Publish post"}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() =>
                    void saveUploadDraft({
                      caption,
                      sport,
                      contentType,
                      previewType: mediaKind ?? "unknown",
                      postType,
                      questionPrompt,
                      pollOptions,
                      collaborators: collaborators
                        .split(",")
                        .map((value) => value.trim())
                        .filter(Boolean),
                      remixPostId,
                      scheduledFor,
                      visibility,
                      premiumGroupId,
                      sponsored,
                      sponsorLabel,
                      autoCaption,
                      translatedCaption,
                      accessibilityLabel,
                      aiHighlightAnalysis,
                      voiceoverScript,
                      thumbnailHint,
                      clipStartSec: clipStartSec ? Number(clipStartSec) : undefined,
                      clipEndSec: clipEndSec ? Number(clipEndSec) : undefined,
                      watermarkEnabled,
                      downloadProtected,
                      rightClickProtected,
                    }).then(() => router.push("/drafts"))
                  }
                >
                  Save Draft
                </Button>
                <Button type="button" variant="outline" asChild>
                  <Link href={contentType === "reel" ? "/reels" : "/feed"}>Cancel</Link>
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </ProtectedRoute>
  );
}

export default function UploadPage() {
  return (
    <AuthProvider>
      <UploadPageContent />
    </AuthProvider>
  );
}
