"use client";

import { useEffect, useMemo, useState } from "react";

import { AuthProvider } from "@/components/AuthProvider";
import ProtectedRoute from "@/components/ProtectedRoute";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  buildBrandPitch,
  buildPressKit,
  buildResponseRateInsight,
  getBrandMarketingProfile,
  type MediaRequestRecord,
  type OutreachSequenceRecord,
  type PressReleaseRecord,
  getDailyNewsDigest,
  getMediaRequests,
  getOutreachSequences,
  getPressReleases,
  getSponsorCampaignInsights,
  getVerifiedJournalists,
  saveBrandMarketingProfile,
  saveMediaRequest,
  saveOutreachSequence,
  savePressRelease,
} from "@/lib/phase1";

const ADVANCED_BRAND_FIELDS = [
  { key: "brandVoiceGuide", label: "Brand voice guide" },
  { key: "campaignBriefBuilder", label: "Campaign brief builder" },
  { key: "sponsorAssetLibrary", label: "Sponsor asset library" },
  { key: "aiPostPerformanceScorecard", label: "AI post-performance scorecard" },
  { key: "brandSafePostChecker", label: "Brand-safe post checker" },
  { key: "pressReleaseGenerator", label: "Press release generator" },
  { key: "landingPageBuilder", label: "Landing page builder" },
  { key: "qrCampaignTracker", label: "QR campaign tracker" },
  { key: "utmLinkBuilder", label: "UTM link builder" },
  { key: "campaignConversionCards", label: "Campaign conversion cards" },
  { key: "crossChannelPlanner", label: "Cross-channel planner" },
  { key: "brandMoodboard", label: "Brand moodboard" },
  { key: "sponsorPackageTemplates", label: "Sponsor package templates" },
  { key: "partnershipPitchTracker", label: "Partnership pitch tracker" },
  { key: "sponsorInvoiceReminderTracker", label: "Sponsor invoice reminder tracker" },
  { key: "sponsorContractRenewalReminders", label: "Sponsor contract renewal reminders" },
  { key: "creatorBrandScorecard", label: "Creator brand scorecard" },
  { key: "creatorContractDeadlineAlerts", label: "Creator contract deadline alerts" },
  { key: "logoUsageGuidelines", label: "Logo usage guidelines" },
  { key: "merchDropCountdowns", label: "Merch drop countdowns" },
  { key: "brandContactCrm", label: "Brand contact CRM" },
  { key: "campaignMilestoneCalendar", label: "Campaign milestone calendar" },
  { key: "autoGeneratedGameRecapPosts", label: "Auto-generated game recap posts" },
  { key: "promoAssetApprovalFlow", label: "Promo asset approval flow" },
  { key: "fanAcquisitionCampaigns", label: "Fan acquisition campaigns" },
  { key: "creatorContentApprovalQueue", label: "Creator content approval queue" },
  { key: "creatorSponsorshipDeliverableChecklist", label: "Creator sponsorship deliverable checklist" },
  { key: "sponsorDeliverableProofGallery", label: "Sponsor deliverable proof gallery" },
] as const;

function MediaCenterPageContent() {
  const [outreachSequences, setOutreachSequences] = useState<Awaited<ReturnType<typeof getOutreachSequences>>>([]);
  const [pressReleases, setPressReleases] = useState<Awaited<ReturnType<typeof getPressReleases>>>([]);
  const [mediaRequests, setMediaRequests] = useState<Awaited<ReturnType<typeof getMediaRequests>>>([]);
  const [advancedBrandOps, setAdvancedBrandOps] = useState<Record<string, string[]>>({});
  const [status, setStatus] = useState("");
  const [outreachForm, setOutreachForm] = useState({ label: "", recipientType: "", steps: "Intro note, follow-up, final check-in" });
  const [pressForm, setPressForm] = useState({ title: "", body: "", audience: "media" });
  const [mediaForm, setMediaForm] = useState({ requesterName: "", outlet: "", angle: "" });
  const [pressKitForm, setPressKitForm] = useState({ name: "HoopLink Creator", role: "Athlete / Creator", achievements: "Showcase top stats, wins, and milestones", links: "Profile, highlights, and contact link" });
  const [pitchForm, setPitchForm] = useState({ creator: "HoopLink Creator", audience: "recruiting-focused basketball audience", value: "credible athlete stories, training content, and consistent engagement" });

  const refresh = async () => {
    const [nextOutreach, nextPress, nextMedia, nextBrandProfile] = await Promise.all([
      getOutreachSequences(),
      getPressReleases(),
      getMediaRequests(),
      getBrandMarketingProfile(),
    ]);
    setOutreachSequences(nextOutreach);
    setPressReleases(nextPress);
    setMediaRequests(nextMedia);
    setAdvancedBrandOps(nextBrandProfile.advancedBrandOps);
  };

  useEffect(() => {
    void refresh();
  }, []);

  const pressKit = useMemo(() => buildPressKit(pressKitForm), [pressKitForm]);
  const brandPitch = useMemo(() => buildBrandPitch(pitchForm), [pitchForm]);
  const sponsorInsights = getSponsorCampaignInsights();
  const responseRateInsight = buildResponseRateInsight(24, 9);
  const digest = getDailyNewsDigest();
  const journalists = getVerifiedJournalists();

  return (
    <ProtectedRoute>
      <div className="mx-auto max-w-7xl space-y-6 py-8">
        <div>
          <h1 className="text-3xl font-bold">Media Center</h1>
          <p className="text-muted-foreground">Press kits, brand pitches, sponsor analytics, outreach sequences, media requests, verified journalists, daily digest, and press releases.</p>
          {status ? <p className="mt-2 text-sm text-primary">{status}</p> : null}
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Press Kit and Brand Pitch</CardTitle>
              <CardDescription>Generate media-ready positioning for creators, athletes, and campaigns.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-3">
                <Input value={pressKitForm.name} onChange={(event) => setPressKitForm((current) => ({ ...current, name: event.target.value }))} placeholder="Name" />
                <Input value={pressKitForm.role} onChange={(event) => setPressKitForm((current) => ({ ...current, role: event.target.value }))} placeholder="Role" />
                <Input value={pressKitForm.achievements} onChange={(event) => setPressKitForm((current) => ({ ...current, achievements: event.target.value }))} placeholder="Achievements" />
                <Input value={pressKitForm.links} onChange={(event) => setPressKitForm((current) => ({ ...current, links: event.target.value }))} placeholder="Links" />
              </div>
              <div className="rounded-xl border p-4 text-sm whitespace-pre-wrap">{pressKit}</div>
              <div className="grid gap-3 border-t pt-4">
                <Input value={pitchForm.creator} onChange={(event) => setPitchForm((current) => ({ ...current, creator: event.target.value }))} placeholder="Creator" />
                <Input value={pitchForm.audience} onChange={(event) => setPitchForm((current) => ({ ...current, audience: event.target.value }))} placeholder="Audience" />
                <Input value={pitchForm.value} onChange={(event) => setPitchForm((current) => ({ ...current, value: event.target.value }))} placeholder="Value" />
              </div>
              <div className="rounded-xl border p-4 text-sm whitespace-pre-wrap">{brandPitch}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Sponsor and Outreach Intelligence</CardTitle>
              <CardDescription>Campaign performance analytics, outreach sequences, and recruiter response-rate snapshots.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-3 md:grid-cols-2">
                {sponsorInsights.map((insight) => (
                  <div key={insight.id} className="rounded-xl border p-4 text-sm">
                    <p className="font-semibold">{insight.label}</p>
                    <p className="mt-2 text-muted-foreground">{insight.impressions} impressions • {insight.clicks} clicks • {insight.conversions} conversions</p>
                    <p className="mt-2 font-medium">${insight.estimatedRevenue} estimated revenue</p>
                  </div>
                ))}
              </div>
              <div className="rounded-xl border p-4 text-sm whitespace-pre-wrap">{responseRateInsight}</div>
              <div className="grid gap-3 border-t pt-4">
                <Input value={outreachForm.label} onChange={(event) => setOutreachForm((current) => ({ ...current, label: event.target.value }))} placeholder="Sequence label" />
                <Input value={outreachForm.recipientType} onChange={(event) => setOutreachForm((current) => ({ ...current, recipientType: event.target.value }))} placeholder="Recipient type" />
                <textarea value={outreachForm.steps} onChange={(event) => setOutreachForm((current) => ({ ...current, steps: event.target.value }))} className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Comma-separated sequence steps" />
                <Button onClick={() => void saveOutreachSequence({ label: outreachForm.label, recipientType: outreachForm.recipientType, steps: outreachForm.steps.split(",").map((item) => item.trim()).filter(Boolean) }).then(() => { setOutreachForm({ label: "", recipientType: "", steps: "Intro note, follow-up, final check-in" }); return refresh(); })}>Save Outreach Sequence</Button>
              </div>
              <div className="space-y-2 text-sm">
                {outreachSequences.map((sequence: OutreachSequenceRecord) => <div key={sequence.id} className="rounded-lg bg-muted p-3">{sequence.label} • {sequence.recipientType} • {sequence.steps.join(" -> ")}</div>)}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>News, Press Releases, and Journalists</CardTitle>
              <CardDescription>Daily digest, in-app press release publishing, and a verified journalist directory.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                {digest.map((item) => (
                  <div key={item.id} className="rounded-xl border p-4 text-sm">
                    <p className="font-semibold">{item.headline}</p>
                    <p className="mt-1 text-muted-foreground">{item.summary}</p>
                    <p className="mt-2 text-xs uppercase tracking-wide text-primary">{item.topic}</p>
                  </div>
                ))}
              </div>
              <div className="grid gap-3 border-t pt-4">
                <Input value={pressForm.title} onChange={(event) => setPressForm((current) => ({ ...current, title: event.target.value }))} placeholder="Press release title" />
                <Input value={pressForm.audience} onChange={(event) => setPressForm((current) => ({ ...current, audience: event.target.value }))} placeholder="Audience" />
                <textarea value={pressForm.body} onChange={(event) => setPressForm((current) => ({ ...current, body: event.target.value }))} className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Press release body" />
                <Button onClick={() => void savePressRelease(pressForm).then(() => { setPressForm({ title: "", body: "", audience: "media" }); return refresh(); })}>Publish Press Release</Button>
              </div>
              <div className="space-y-2 text-sm">
                {pressReleases.map((release: PressReleaseRecord) => <div key={release.id} className="rounded-lg bg-muted p-3"><span className="font-semibold">{release.title}</span><div className="mt-1 text-muted-foreground">{release.body}</div></div>)}
              </div>
              <div className="space-y-2 border-t pt-4 text-sm">
                {journalists.map((journalist) => <div key={journalist.id} className="rounded-lg bg-muted p-3">{journalist.name} • {journalist.outlet} • {journalist.beat}</div>)}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Media Interview Requests</CardTitle>
              <CardDescription>Capture inbound interview asks and keep a simple in-app request flow.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-3">
                <Input value={mediaForm.requesterName} onChange={(event) => setMediaForm((current) => ({ ...current, requesterName: event.target.value }))} placeholder="Requester name" />
                <Input value={mediaForm.outlet} onChange={(event) => setMediaForm((current) => ({ ...current, outlet: event.target.value }))} placeholder="Outlet" />
                <textarea value={mediaForm.angle} onChange={(event) => setMediaForm((current) => ({ ...current, angle: event.target.value }))} className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Interview angle or request" />
                <Button onClick={() => void saveMediaRequest(mediaForm).then(() => { setMediaForm({ requesterName: "", outlet: "", angle: "" }); return refresh(); })}>Save Media Request</Button>
              </div>
              <div className="space-y-2 text-sm">
                {mediaRequests.map((request: MediaRequestRecord) => (
                  <div key={request.id} className="rounded-lg bg-muted p-3">
                    <p className="font-semibold">{request.requesterName} • {request.outlet}</p>
                    <p className="mt-1">{request.angle}</p>
                    <p className="mt-2 text-xs uppercase tracking-wide text-primary">{request.status}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Brand and Marketing Workspace</CardTitle>
            <CardDescription>Manage campaigns, brand systems, sponsor assets, conversion planning, approvals, and acquisition notes in one place.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid gap-3 md:grid-cols-4">
              <div className="rounded-xl border p-4 text-center"><div className="text-2xl font-bold">{outreachSequences.length}</div><div className="text-sm text-muted-foreground">Outreach sequences</div></div>
              <div className="rounded-xl border p-4 text-center"><div className="text-2xl font-bold">{pressReleases.length}</div><div className="text-sm text-muted-foreground">Press releases</div></div>
              <div className="rounded-xl border p-4 text-center"><div className="text-2xl font-bold">{mediaRequests.length}</div><div className="text-sm text-muted-foreground">Media requests</div></div>
              <div className="rounded-xl border p-4 text-center"><div className="text-2xl font-bold">{Object.values(advancedBrandOps).reduce((sum, items) => sum + items.length, 0)}</div><div className="text-sm text-muted-foreground">Brand ops notes</div></div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {ADVANCED_BRAND_FIELDS.map((field) => (
                <div key={field.key} className="space-y-2 rounded-xl border p-4">
                  <p className="font-medium">{field.label}</p>
                  <textarea
                    value={(advancedBrandOps[field.key] ?? []).join("\n")}
                    onChange={(event) => setAdvancedBrandOps((current) => ({
                      ...current,
                      [field.key]: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean),
                    }))}
                    placeholder={`${field.label} notes, one item per line`}
                    className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                </div>
              ))}
            </div>

            <Button variant="outline" onClick={() => void saveBrandMarketingProfile({ advancedBrandOps }).then(() => setStatus("Brand and marketing workspace saved."))}>
              Save Brand Workspace
            </Button>
          </CardContent>
        </Card>
      </div>
    </ProtectedRoute>
  );
}

export default function MediaCenterPage() {
  return (
    <AuthProvider>
      <MediaCenterPageContent />
    </AuthProvider>
  );
}
